apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ww8hPBHWau5KOBcGvvrIx/6vS2PEtHRrCTR+9lDWr6cD9db3dZ6P+w==,iv:vb2wU0mHqbQLyLD6GZHksftOSW5dvA5ifdRCWtpU7Lw=,tag:01UfhggvJDPTI/ykSGStpg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZXJMOEx3cTJ2LzJIT1Zx
            QTBMME04Q0dKbnR5UktIZ25vemZsY0hBRlRJCjJMbWpKVDA0YzRMeEdHb1ZyN0Rx
            cFFaaWdaY1lDTHdxcE5FU3U4ZkdyeHcKLS0tIHkweGhpdGpMYzBlOGlDV3U1dy9P
            UjJFV3ZhM0dGempkdE5GdjFTNFcxYkkKsG/3eleA/F5v+pLop910PziVK2WLvnq6
            JWOpdxX802NAq3KgtwkMpYwvoZO6k5mv/nerRR/CMFoqvebYm/UMMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T14:40:30Z"
    mac: ENC[AES256_GCM,data:iGMdDDolTFsLTDuD4Vqn9PmUPF84TTy77156WJ0VaXC3n6plHpioXhoKMDoOwjOu13Khv2pl58NmIoeDo/xmM3RcukHALSpiQOxhnw4oPW6RSG+mjXrxyur98nH4VCLVwgSxSE486dC0XICYXgJBVG7ovLDvS8MgwLz44cbxe0s=,iv:pcfUAM1E/1+iepA5rZTnd8u0VhWZS/8rezGw5E08j+o=,tag:4OdrI/28lSR/WtFUzLrvbg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
