apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+EukiG2JLPMBOEzLyjt7VZosTScR+4HGmDDu0MhrmhLoYO8BabqJrw==,iv:np5DK+TaOH4OjAaWbyUytcJOimRqMzJNoy3kqSfQWn8=,tag:DK49Pxin8htiqth7Jskppg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWHNmSXVxQm9xUWlGYlRU
            OWRTdFhYdEZyUDc4YXFLL3I3b2oxa2ttNTE4CnhQSXA1ZTZDNWI4SzUzMjJJbGlx
            WDF2Y09weWpSblhLVktpNHRIRmhQVFEKLS0tIFErT2grdHE2RzBwKzR0RDJEUkVZ
            RmZIRGdyWjBBZExaZHhzc1NrcEZoS28KUflnn7Ihrv961qnyNHhe9d9bDmMKNtqO
            SjecQIbYN5sY0jl9QYeX/IGtye/8GdMfnfv9H5Vd1hv3DirKey1a7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T17:01:37Z"
    mac: ENC[AES256_GCM,data:RCI45LBQK/TZT7HNAVZ43oGcTz1X19jGekA5zHKi1cvUG+x3xsEUqQcV0YnREUzPKgieWd6GCahLMbGLfUWvakyUc91YA29yEMNjwyA07gxwPDybWGCXqMPB5v29mlWXweOFTnI+7keFV3/85GcEBn1PEUUPu7347j1dMts4JFo=,iv:Y6IYCgsqR7fhirdpPNGHmyeQHY+8UV0xFe9Ovtrd5rg=,tag:VkWd2Z+Gn5pAOLMRlUm4Og==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
