apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:UlOnXLUN2tbY55m1rNeSli1sk7YabXx/eLit5+qjUUGjytefFcXURg==,iv:0f6gnwu9XtUHX9UTpjJxHrb7VS1xYHeeI1yk/ub/qwQ=,tag:yj8RD1LeiSTScA79VFJUiA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiREZ1bk1PUFVoUGhZTndm
            a3J4d1pGYlArMUVmMmVieEp2SitSOEFGUEQ4CkFhTEVsQnNZWmJYNVVia0RnVGJp
            QVN4UHp1ZnRMSzV4NWlCOU5FaWlFQWMKLS0tIGE0TGx1MVVJZzlYbjkrdXFYQVJD
            a0JqSWJkOThpQ3NGNDN6VWpBRFlyREkKf5AZDUYwDEUmiTBkoSwq6uBSNwtGkaaj
            B6XQ0AF1O/xo+GSqrw1lpUtZ5Fgq6CZF9TuPcdpJcyNNco7b4rfdAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T16:01:11Z"
    mac: ENC[AES256_GCM,data:rVkL0j10FiuogqN18THMgD0aqWenwPdSqEPYHXqnaJi8N38HrxTC+8bTpuwCnrjJ6F7WJ7+mGf03YTpyZpU3mFF703qpwLnIiDA8aW532NfJrkoyWlvCt/r/OBREGt6a9Re0ouvmwgUb1P8SE4w441HkW33p1QopkO3ctM0bd/0=,iv:DCxICPjrlhvkpxGGGOrRNkf+3fZcSOy8aMuEuvAfWdU=,tag:MRo5b+05XaZfymfVLAzxlg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
