apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:MBbvVXZo5C1EcZ/2Rw227i2GrYib7b/NmGBhLwEBx6E5ICgExfNnOA==,iv:qvlqozqw7KMoSuvzQo3nCqyh6wXBcRGY7nYZAAeLLHQ=,tag:HNSiBo1NKghfuyWesU1gyA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aVQwUnl3MVFyVnRUWnMr
            bmRQWm5YU1lBZUZ4ZGpFM0NDN0NrOXlGWEYwCmF0ZDlwZExiQU5HcUFEV1VmaUY3
            RjFRNGN3NDNaUHVNWEZaQ3JqVFhjczQKLS0tIHV3cEtwajFPZzJhbTJsSUhBdm15
            a3dicWZrZ3loYU5xb0VzdllsM0dwUWcK7YMSE1bdnyVdZRYEu2RxSJIeX1JwAShi
            qIF4bhMwrITBAhZQCv2k4tR0xO31B2xr0wAUmb1PmAj5MAgCCDhlYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T14:49:01Z"
    mac: ENC[AES256_GCM,data:Evzl+IZNkZ5ALYYfVQWmCGpc/iMtz+zAdT4PSmsHRksAJ+0gue2KStm1kCdSTIZ8zfdfFZnBGIOsWChreg9rfVXjWxRCscCnC3dmycQokpSY7u42Efso/fVSOtp+ROj9Wo9JVThhWp1nk0WeDuWpe9XiXQJDqjvIgL05FgNWspg=,iv:4K9U/FqEvca12xCxv3NlzVdjrRb+I9HTT8rjpWz9MNQ=,tag:CPJp/yAiyHNSJh1EzuM39g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
