apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+Qxl/wfNP7WA6LuLRzHWDR13d1KSxTKE8/PCIO2JuDYe7VAJ8aHj2g==,iv:qnj1cDGmb610mPAMH5MU7wuqpSs0yTLoIcKGFvZzX88=,tag:cCZ5jGtENWnBgtkzE6XELA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibzFibTlQTVlEOGdYTzJi
            WHRXS2htMW81SDhlcHlEYXZDT3Y1S25uV0Q0CmpSN1VFQTJhTDlLUmNyYmo2eVZP
            RnpMRUsyVm5pSGNNcEpoa1RlNlZXQjQKLS0tIDdWVU9saUg1OGc1LzhsY1kyT0d0
            WXpBeHpEZ2U1dU94c1JyZ3Vldm9zY3MKNVUUvrQvnoeGROn3ErEWR0/RyaaLWUre
            Fo4O1aPY4lZGlOZArBknNHQpBLKBVvogDG2aJjtnBys3V1w8+tm9tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T20:21:36Z"
    mac: ENC[AES256_GCM,data:oHbXQLzo2YRRJhTQhJB6VuWs3Grw5+ZBufMTx6gV7P7COWZ5QKQrkiOAkuj099DnXIfCdQbjnSeJxMZzKlPRLUxle4CSM78EBMUxleTD39lAWqjvUjn7leYUNedYnfX7Uya5RQkrD6tlVvIia6sOffmE0D52R0XVwujiORyE/Hs=,iv:fE0IPjIXRmxXK5AxTYaawSBy5CGbS9zfAwl7UZtcaMk=,tag:PfRYY6OU4cOhRhmjaxFt2A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
