apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:V0NIk8zny8rDx0+AockUDBc2e5+MaltxJuXu1nZXP6sMm42z1IAWjg==,iv:CpMAdYiB+n6YH0hmuvMhDrc6y8LS2zCbvaBfNg8/w9k=,tag:jlwyl9ynLkoCAI7m+XE1lw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFajNyU0FsRXZuc1NUWGh1
            bFZvTlhEcnZzUUlLTWdsb09LaFdISEFnOXk0CnJxVzgrc1FQaXc1S281U3NEOTVi
            Q2dHNkQ3ODBmbDZKSnZDSVNKVVNFWkkKLS0tIE9Cb1JLdy9xdnJQOFk1QWw2bllr
            RGZTYlBsaDFQSFp3VmZzejBxRHpzTjgKgO6wtB385Y9d5KvYFr9SW18PTLlTMO8M
            sK5PdltTUVsPLMRaPQ/QrwwLvodLxLDC3+aT9WjENUiceHJ45/JFCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T17:32:36Z"
    mac: ENC[AES256_GCM,data:yL8C+TePg1ZYyWSccqKBQfcbBWxno8oSwhVvHgU4oQD1FAnmoe0UliXO+YewTCHvgLeZlbKEYNhXmFOaSBl7qFAiCzpJz/aPQh128X02VfW/IzyxBC8kbDb4sMqP7vGQpb5U3DE3yvjk4WJzeYnm7Le9t7ZqjcA2Zv8jWaJIbUI=,iv:l4M+8xx9kinU57ez6bMCKcm30vuwDUz4XC84CDofjSk=,tag:nO13fJGKItLsWPnWxqhQZg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
