apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:prGESz5g/nUxA96Z/9zFISrPWaTuD9Zy3/4XAGlgVKMG6ILttrYARw==,iv:ri/Ws/oPn1pp1XEFbLqYHbPU/qvp77E5CzrK5Cd0t/Q=,tag:zSTRSdr9B4RirHodcJXWJA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWGQwT0syc2FEZE81c2w5
            cW1GQi9SUExTNXloK2tvek15RmUybjNoVndFCmlFSnE3R2VhV3JLeks4U2tIZGh3
            TW4zNXpTOGhOWFUxYWlURlhhZFFwSTQKLS0tIG9GTm5RalR4LzJwaC9uRTRhWUow
            NlFpWHBCQUxzYU5Mei9tQURWbE93a3cKi4+DapwZ5wcFmgusrRZ/YG6o32LaAlCA
            JPzfGjNxr2k8BRNIQgHWOTJD6uggMhajmsX6LvMc5L8i99e8eKwNHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T12:49:32Z"
    mac: ENC[AES256_GCM,data:iFys/i82hR4A+yyPW8pf8GoraNwjdggt0MK9owbbn4vQkKFeFgVAxJPVIKCp6Hexe2gIRX5SW+D3GykAb/gxOH1ZFOTgMEzGLmeYCjVR2Qm0jgI+cSxY27GVZY5/P4eVG+ZaYCZ8uJoSioamRAb5a3HIvtcZvx7tM0yZI2KFNSM=,iv:lbd03usoGEU+w4/Jqr0VmuM8Dkwa2m0s1AWTteqwDLE=,tag:tGRHlsdrrTVeOiJBOrqWdw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
