apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/5XDdj8GsnlGSXSQc+FWT6kWuoURl7NQBlCejKBeusn6LopmFxhr4Q==,iv:TB6IgsCbKV3ixD5tpafx8L0zetOVHSLnzd7gIRc6TvE=,tag:V6qSs/yRpyChMaxMzhN/mw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTFdaOTRsQ1JLdjkxRWVs
            bnFHRDZ2cmxBMDZBY3RLRm1oTURKU2F4R0c0CkQ3Mk54TVVDZkMrMmVYMGFiN2dt
            ZzVJMkVtNjdhUHhENm5ET2xkRFF6NFEKLS0tIFV2aG1IYktoR0ZzcHZVQzIzV1RV
            YlBENk9QVk90SlZJWDFXclgvMXFIQUEK2wcMtD212IUjhuaK5ekiCVGnZmS0Xvtw
            ux/WvJ3xXGOf/VhK8vnj5qx8MbYpKHH2orBid92L+wWf39eFxbSoNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T22:19:38Z"
    mac: ENC[AES256_GCM,data:woYeD8/mFI7F6baLwNvfel51IutHn/lTgniMxgxHg31Kc3CAIkTPcSZ2sFpRSqYKmKa2nGNK9zbj6tD0bxn6WG8z/jq1Tiqb5JjJ0OissRmnLeuhR3pWJL/msU6eFNFuX3N2pzF9PR5J62HooMzKF8T+thjPUY1qboV3+6kZ1oo=,iv:8+rklG5lSuGoL/NJiAs2iDW0uVerbcPOUlKjkWMZnG4=,tag:6PeW2X1AKaOx4x67EqpX+Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
