apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:N+QgPtg4JM++IRnrMtO1gVgLBtTfO8mgu+keCKKXeBddrcON0Ip1vA==,iv:7qyhqGYONiTCLklYp6IYcVORuO+LhmlGdpkEZrm4Pws=,tag:oxXYw+RGxltKlY8MMLasjg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVTArLzYzUm95aXdYM1VM
            NmlsTUNVRlg2UWJWVXVvUVFqNE5NOVJpYmxRCnp6QnoyellCaVlMdG9YbC9ycEFs
            ZGxxNVozSkFTUWVaTXV6YkdraC9JcTQKLS0tIEg5d1Rub3o5bDFvK2JCNTFWdUFS
            STc1cDZHNm5GVkpaajRCUWt3aktwdlEKQChkEuJBRzts6q1+rwKrtsbZwoM8W8Ey
            rJ6nB5HHOTzPRlR25tweMi1+zfXW69jbwLn+Hu4px3iXeUu+76Q/hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T22:52:52Z"
    mac: ENC[AES256_GCM,data:JlSD2NApeyMzhnA2EZjYWpLfcxnq7x3MQEzIKCgEb0jFc/mQJvv3mX7J2qhS5O9CaGZP0Dk12kivfaBqgSptQUeIWEvIVVIsGrOa5HadAvg7lMwSJ077lN5ZY0oNLys5Rsb9afCev2+2k+XyvC+AbxKJ3pd0Uif5bUrVz4XinvU=,iv:yufp28eZh1wJ0NPubgzUtvPrSm06OEqE1lXv3+0m5gs=,tag:Bv4E/KV37+VmahGFSYbIDA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
