apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Rj1xCpMgsCgDo91jge8hcpg2PxcLv8ZeY2EQeP7q0Lrc/RNLgmY0PQ==,iv:WQTyCQ//7uWXc05ua0SjxvKfZWHTVYOgoeR/2vCTuGk=,tag:QVwlXFFEh2leC2vCVmGlCQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNXhQcHRHa213bmpGVVdq
            OVJwaitXazg0UUR6dDNKNjJRY0xpNWxSTFdFCmRyRUpzakVSWmxRUGFFV2xHSkwr
            N2dTM1cxeHVXUmlKRmdreEZ2RDR3SGsKLS0tIG04RkgxdFNLSCtkTDFUSEdUN254
            QUJXcmZyWHl3Y1N4RTA1UXpubjFDbEEKJomtVC9TwlvohfrvMWQybny2xsCv4kKP
            qANMgLpMADLG7HcqbTu7TeK4RJVj6pfsgtwlProokYDXFqd8FelO4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T12:10:33Z"
    mac: ENC[AES256_GCM,data:TC4dGZIAVMn8Yxuy7W6arBW826ROMDltNKg528+hbqWD4zl2kxY7reW/VJ5yy37kpC6c2rXZYcxaRsgMb4N7MG/zOMVYCM2er0nhlU4QOwxLM/4AmOb92tfdCSTuX/i80rmLXqVxwHODfC54nSO5tHUuswpLhRI3esCe/qESEtY=,iv:TcIq2lExAOUh+tkDkBBPQpRyDH24D3H012XP4ENqpCU=,tag:00xwWvHiVvvGV/aiUGz5sw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
