apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:xDAIXZvqb+ZAX7btoh8zH2tZ60uXAkAp28KjeeQyYH/zgsN9oAOCyQ==,iv:3fLMj2rNMzjuqogUcEfn0hfIc9p36qSwUE1AHIspMIw=,tag:IDECXxUmdxhej517Crbo3A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eXZ6QWhsNFF6b01MU1ZC
            YVErbnNDcUJFY2VqRlBFVmlvaVBFUzlPVjBVCnVLVzYraklFNWVBRDVsMWR3MDNs
            ODErbG13ek9wL1VGR1ViRHhyT2s0YTgKLS0tIDVjTzVhUmVSV2Z6bEd3RC91OVY5
            ZUV5NVdjRlJidnlKbzg1SXV5OElCemMKifWC9uGxrEhYnSQjwCuQImg+OB/8yt8s
            k4wEuaTGyCtMXjhQzb++Wc+mZWLASALWDcu9PfhHCFWhsT95+CRhwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T21:24:37Z"
    mac: ENC[AES256_GCM,data:HQgmPgOBvxYsOjekTMRTxIt5LHvb2ue/G7hnSQdREUPc1dUiShQNj7WAiFR7pMfNtLzaj4NfuIWL7ua9QnFH88vjHSsSy4OkPIuGnqH7gnk1AzbyoGJ3nmpEFFjYiGtmkTRg3VvaA1CG67F4ltImuG6Tp/ksdK2t5D31WFgPKjI=,iv:e48hKxxWl50av4t3+kDYr0ctKjUhIO37RPfMTPmyqE0=,tag:Q9tzK8NuNxuG3yR5kNm2bw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
