apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:WDwVgqJZ6GwIiKtc1gGGaw4iies+VrhRWn6gh/Fx9Hb2JdHi9DLEmg==,iv:zLcfPBxDqF8MBO69PXNVPN5E9cF+DunizeicfqF8NlU=,tag:eRaRRMtR85wuXzBv2ReniQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtd2NEaSsrNU5mRy9Ed044
            b2RkUlQvRVNZeThES3lXekp4Vm8vQ3kvaFQwCjVFenkxVXB0bFRmWWFVVUhuSjll
            cHZUT2I2OW5kTjdKcnFnNnA4RlZzWkkKLS0tIGlRRFRuNGFFS1FjVU40MEg1cDc1
            N0s0SUJBNHArV0lnZlVSVFZkNFJiNVEK4EcjVeRCY7nbHAlLAeEVg2Bxmb/2C3CM
            qclrMc2Y2ARTC6yH1/gBtLUhTrFYEoZIAyHdM1oZxKte8kVFjzwSlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T17:58:12Z"
    mac: ENC[AES256_GCM,data:rpkDaYNmYgpRnMRNm8ObzhlsFAPHsC7JturgXvuYl16owJvXhsKcnJ8y7QTzo6Hbec9vFik5V9iWMajxjgcBO1TMka7PyiPKxwov1EsBo/di87Ph6hyUXRSYMbpu45yBOY3eShy1S+suuO4gzl8hI/wFO96VOEsBzW3pgS8jJNo=,iv:nppfzuo81GFFfTL0dOvj4z8ka21rT9lab3fHwjKXv1A=,tag:ks0hRCvuR6T1t6jhMJLLbw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
