apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Fo2Qdg1eAl0U62rauiP9kgh13hXkdfROzp1IhpXdYRoPsF8C+p2TEg==,iv:F/2vFrPNuRx2PSEutoVCdXaqFJNbM+XLe+VdT0seMqY=,tag:eoLzFAa0UX/PeGZENCQGpw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWHlQNWR5dXVuQzlxTXh4
            aS9lWlZIeEgrMW9IVWQ2Q3hYeDNPV1AyQ3pZCmx5bFl5YXRaNjIrYVIwTjRnME5H
            RjI5R3lEWE8xTzlTdmJsN2xUS25Va28KLS0tIGgzRWR0U1crd1VPWTZQYUNCUmpr
            MCtYSUYrN2Fld201WmczZEdkYzFjbGcKoU7WEsoRNI6drK4jrUdaahGoPM/C3uEW
            +IwgM/VwISyFYTOYkvNqxugFoEYQiT8E91pXkqyZV+h7XqbPiH0RaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T23:11:31Z"
    mac: ENC[AES256_GCM,data:bQYegcEy9G4pSUjMCaFyqvWhq5Ki+me08/TUNxqAamg1oXTiimymr1jQbT/hQpqt1sSCh1uHGuscWQJq91YTms4T2I5gxP0C57WEtIpP3oy+I9LHv+xkRGximdbTrNrRujq0ZFl+aW53C8OIW5LalQXYPkr/A88B/Oeq31RdcfM=,iv:OBPU75i/sZ3K9615vi0OyiCmX8F6iM7bq/CACnWPEU0=,tag:epPUdaRXv3LFRSIHL0OrAw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
