apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:7SJu+JrEpGvX0ZMpyM6kbbVRNj411c4Ai/Q15S25ONMoRrJZHR17Bw==,iv:UElwu7HerJ4kRenrdFFkm+8Cd8t3h8JNUd9Pn/s/dqA=,tag:gvvhO3PVUzuD/v/uEacUDA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWmV5enI4R2FHYnZVMkxr
            VnNXRE1aYnBYTElCV2dRUG4yazIrNEQ4SWpzClRmdEJMZ3cyZElFa0pUV0ZtNUV2
            cVJIdjJMdXcxL2RIV2dwNlUxWHFOaUkKLS0tIHhSa0xqQ0lBRC8rdExQMFdUZlRJ
            MVlRTk5GQVFDVDJWRGFneFNTaGJKSDQKFDzxSHByJCrIooyqeAmA8Nhus8rPkQhO
            oobcdU/UE7SUjaAkNUdM8T/LIQPjWT38xnH1MsxG0erruwmPsj2stg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T16:17:39Z"
    mac: ENC[AES256_GCM,data:k5iJv4pGvMbgA8l/pph5G77BXa+0YVjorIcX4J5bb+ClbXcmDVqSU+vUTpZLpiqpWkVBQyUh9X/CJaK3hMp3ZHYDJateVLtRaP6ZLw5e/J3qz0v/FVE/FnZOFQ+xwgSOECGC7TpWaZMvy97dog1hBigpUDPM8+l+mTCFOGp0MRk=,iv:hCDeXiTiwZM566WX+XFOeSKe3zBmmrwgHM53oXY/ihY=,tag:Rme4dN9YRlT2uMQSdgu4Yw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
