apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:uGyVDgLXuav9HijNw+EUiaP7y8XSfqhJ4XTKc1YcEysfDCDvjS8P/g==,iv:M7V7yDy3vzbK8mzdc9DPLwMSWm49L1tN8pEa/ysUw1g=,tag:7VIaIEfCyMWObqdjz/cS0Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocTA0VWwvaDkza0tRaGls
            Q21Ub3RDMG1WWUhJWGxPSmZmT1dSOEVoKzFBCkdLeXlkQlllR0hYdnB3NitZQU1r
            NkNRQVBaMFdIdUFUdW9kSk9HVHpaMVEKLS0tIG9NWnRrciswZmI4Q0VoajBIN3pL
            QzMxODFPNnFRd0MzajlYUXVMekg2dkEKH9r8UQctr2pK7dUvaI/J5b1V4TVMQdq2
            6xCPBH5H0QObMeMchmzDt7KWVvcmW9ZEfljScxpgdkrS8JNBCYkN3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T15:48:55Z"
    mac: ENC[AES256_GCM,data:mXtFJPaRm8x6vzos3tRYFkQd9kZuvY7E3/bAPdIYkFscf99HUNk4N0SQ4UgQuetgg/7YXcogVKD2t2nRRj1yqm7THPY3gSzZFnqoeWPrn629po5yRbwzTOv1m/SGZjTHeM+2787MIkWC0fia6/OIMbF8T29xy0hDp8fhAq26f6I=,iv:JelMqQby51/iCBsHQCHkxeLTmTM2CKlHw/SYk34jCV4=,tag:uS+GQELoYl94Fu/0oMb+7w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
