apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:LVIegCwOKsPqKW4zDr2AH6ul1DQHZqHfy486m0VVnd4eb2N6sS2Faw==,iv:jvFSi9rqDbf3DdJAydDApPddT0Wbjl5aTaoz1SGFm8g=,tag:p/BwljhKI3tbj2m4/YciPQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPY05pZnlSNDRNUzBHT3dj
            MVFZMVFVUGlmMTcvWDMvNUtkT2YyVE52eUF3CkJVeFZOenBBYTFqZloyYWFtYjJB
            b29LeW84UkVDcmkyTENTaTcyL2VXUkUKLS0tIHFsb1ZJTUxTN29zRndUM2lLUFo1
            OHhLVE9NUU15dk5wa3gwSzJBS0dtQ2cKbdCDUMBCdJaubGVFLxdDt9088w4jwGId
            y3PG5Yvbqa731BM+Z5xiP9bbNoBbB3fKGLGjZjT1Jo7fRoNqJlGomg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T21:12:27Z"
    mac: ENC[AES256_GCM,data:gHSdWFGdZlGSBeX/OICtNoANLmiycMAJglAo+8SJquLGBYFw2WaRFa3F1QgKBCNAtFX+XPlGRaj0TzGPJoJK056JrK7qeuBpgwVBfk6JpIZdjzsDq6Q3U7+CmPOPT0dtjfA7cpTSpMwL+JzzaOKqlJsCUnyVSbB74Q4UOSa4P+Q=,iv:VE5ci0Sh1B1iyz6Ei9ZPv+LkAOy2U+25OEn5d2gNCpw=,tag:5HdYzt7jgj3Tnu8O7rnfjA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
