apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:RGGV1emGqNtfQoDx96Sm4Tk9uyO4DxSuO4OiYufV1Z8jx5i41rqzmA==,iv:61OTM8ZeSvGa6/tv+m8UjbyqJzj0NRVqSIzJ5RyLAOg=,tag:Yphlsf1mR8RLNHxgPF4bGQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5K2hVeVZFWFMzWS9LRFpF
            YzN5NWJzTEVoaWJVTTFQR2x0Nzh6S0krYUZJCmlIRjJzRDFJYmNRa09oRVdwZ05C
            d3FjVElJbUhINi9GOENyT3lnUFFhL2sKLS0tIDdtUGFrTjZCM01WN21vMlRHczVG
            bVlyeFVFOWJkejZxQ3lUZ0VldVFZOXMKD8IwbengRw0iJR4qeUmIQS3cNTWANzvG
            S7gUZ1tyomq5wp8M3ROVkYK4CIzA39G1SuACpNuwgu9TAV+2JRUi+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T12:49:40Z"
    mac: ENC[AES256_GCM,data:QCjeBjxgH+qWtarJWTQPidy0NIaxjClbUprAQ239uA1Z4AVZiICGdLUxBWwPuvTBWbt2EQ3TZu4A5U4I7mfDDPGQjaYJDYk6iIMFC/X9WtH6gC9ab3MQ8+9i0AH20Hfk/9O2A9Y6qgRpbgKtIjxy9TilvHVh3SI17PdBYJ7i3Ec=,iv:UwgatUSUzicr0Kqcl2B/M69PyrsKt9DYYP5C1dBIPPs=,tag:bWIavE2JjSUz4PjiS+lPXg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
