apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:AHRMNNjm02wcWJylKzrnDXcVvLX2VRhhzFmwXkdlb+njyp0LzUcVXA==,iv:qXgm/lRfGJwOTYSfgPTYP2Ewuxc0IWAwhv/MfUW9SNw=,tag:sCpZIfSFyHp5yjTfS5RrIA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZVZhVDczcFFad0U0MFo3
            bFNKd0dhaEV1ZUlXVVpQZUFVMEVMdEdjR0NBCnNuenhLKzlpTFU5eXZQYnRpajFw
            Q0F0bzBhRzBEY2FkRlNSMWhTdnBRQnMKLS0tIGdNb2Q1K2ovdWp3TEowUG9NMmZq
            cjNaa0tQbGp4d1Jsc012R21LVVB5ZW8KdGWTs/XCxnT1To/fReCaxJd1rNYIZssy
            OpqDantaJjZkcYiYsOh6yk3xnObPPWv2yHBrNOBOTKPwJkCt6uPKbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T20:53:58Z"
    mac: ENC[AES256_GCM,data:8s9CqReUAMToGHd+Y5oDmORtnzFvKMzYMwzL4eMT1XlG8JbwwfwwEEgNQFzl33e/YlO60NHOg6bbkqw/1w2wLoIzzRB5KHNGnpsXMOy1mXhuR1g5lEecLlR36syeFlnkDz3yN+eYw8WBr/Oul1kmAfR65p0tKNIACB0z0kxn4rI=,iv:22TNO7zq8Fwci/T0pAtVp4RRkgYwzIefVliF3XmzyKg=,tag:iilMe4LlH6ghXlO7X1CUXQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
