apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:oTbvDxwrOdERxgqvg5ZAT2ofzvMmz2pHjYYSfZTD2BVBQNS7XzJFiA==,iv:C7rFCFXuHZvuDKkRuAmw8mEaUI4HEp9ezy7tjfc6MyI=,tag:3hZ7LE6cgNjVZtKBTykBtg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQk44RXhObm96K2JEUFM4
            eWhPdVB1SzdOdFJja2FoVDdLUUhpQ0c0Z3hFClF6VUE2bVRuRFVvL29icGRQbVRD
            dW8xVW1yNSs0QjdFbkx6dzZYbHV1V3cKLS0tIEo2UWVTQlVBL25sYVdjVmcxN2hJ
            S2dHRUh0VTA0VDNWSzBxNGpzRjNBOE0KT5nxSWrK+D8D2b/VMZPBIdR1dpMXFTjb
            iJfXU6eLHiC0wMzY22wItULWDSJnhWA2dp2WJWdg5RVV3Xoh9kyOuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T12:18:49Z"
    mac: ENC[AES256_GCM,data:n2egRThCtrHbv8FEgK/lzsXEZBtQ1EUPbNOcMPWMJtV6WKsPchUbKnvNrOPKDD4QQcCEP87zmRQXBkGBT9HFKWVCE3jnSbl/uFsMWxFK8PzeAn0jWExxnU4bF86g2FMRZFLPzdWNJeB6HXzMaX6GTr9KUgu97bsf7tjg+RVdse8=,iv:L4S+Z5ingNwBpOHKynH7s3X1L9svwryJoQ9kqUTvEIM=,tag:i7koZpnfXT0ofj4uy42RVw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
