apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:gVy2Ng7lrkGDMWrkaRlFhlwn3f6iVlZPCJ9tKDz4VweJwpLYn1leyg==,iv:FzT3W5nEb7Od5yAOeRCv+3VPevo8MbUhdZDu+kHCui4=,tag:T0A5ZNrCktxtXNCBJREWQA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZTBNaWROeGNwTzdTam02
            bThQZnhCVjJEN0F5Y2U3SUJzWDVoL0xubGhZClFpbUp0OFBZaXpuZEx6RzhaR25S
            Z042c09ZQ3pwbU9RUHJsWC93U25SNk0KLS0tIG11R2Z3TkwycXUrUU50UldQYkUv
            NVVtMWRGTThRVVl5VVJXRDliTGFlSGsKEvdFKfp32evwosXg+S1uFFMnEJKcP2la
            TiroKUkA78i6JpZdHSG5Kcrva41fqb40y8u6ET4V/Beo7rKTxSThSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T14:39:19Z"
    mac: ENC[AES256_GCM,data:sSt97ayK0J2WxuMm4hn8s7+xxhNgxARNJFsH4pl0v2hhocDWzknjNSU6RCNMeFIeKh2W4i3ZjD+gE9c2xEbyu2tG9svTa1rf+SDTH/z9Q+dccYFI+xcAb/z5aeO9qgMZmivVu3bsKJOQtB8rNxDolU7axLw+nywOwU0pZ4NMqKc=,iv:FtaFa1P/tMSpXnpT/T2KATeCVE0dxxdIFtevWNqPRgg=,tag:UuSW9Sw18MqfMbmKfhr5lg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
