apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:NohjAV8ryZ7LwmJkuW/aRxLC22maTLQY4BOZdZSXQYfOeLYjy38ufQ==,iv:3Bz/0LoOf589rKOxPBhump+Zq684g8jccKR24NewJ7M=,tag:cI528kNqAl+DHBr519wffQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bDNVcUxSRHhMQiszNkUy
            citYT3JiVDVuTnJkVWJjSlB6c1g0blZ5WFNBCnc5am4vSU40Tk1LcTQ1WnlXZnFX
            dmVObittKzF0SkdMYjU1UnliUzcrUVkKLS0tIDRCY09naWVHa2tPbkE5Wm13cVlH
            SGpNN2lMaFlUWXBvMDVNaTYzc3hsL1kKCfB6AvMCvK+WS1Ej50V8wh3bmF62VCdC
            r2pB6n6whzp2xCnkFz6rUzGKmE5ztXMJTy61CP5O/mOzxPj897FS+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T20:40:32Z"
    mac: ENC[AES256_GCM,data:OOYWRK4DVJ+Hft/yxvhm4c0xLvm/3Lw81eRa5LCtqKGYxiLhr9jiX63T1ipnpo16v2Y+Vwjruesopdau0gXvAZ/BdlA7IcnEt5sNCO+4x1wZBwhHIdmNVGLRnCZmmqNO5POyZCFU01w5PVPWV4cq/EtEvj8RSlVyw5OIVH+v01o=,iv:ZLJ3lhwRX5aLpHBwIrLq0qWezpqPZQ0jovIVWAS3L2g=,tag:M2t2JMwmTyCqBSt4ttlq/g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
