apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - renovate/ks.yaml
  - docker-registry/ks.yaml
  - actions-runner-controller/ks.yaml
  - actions-runners-truecharts/ks.yaml
