apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:3ThWo7qE9yPgMZ6GMDaN/gVAkbChp2kiPw2kRYDb7l7P7n/gGeSY2UIyNOwa049/Pvxl0aB1HqBo6jTP4Jxhuk/yxMbHT0BWVe99fI6a2JCKOTkeacXzuubKt6eaIbE29cc1Cr9c+E/ZO+YvP5MwWr+pFiss7t6yLA==,iv:YLTTidpPRlUgGKfZlt1picR0ltEVOYptuKQ5izogTLM=,tag:SUJ0Ggv1m3ecWpahdfHihA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSnhwMTNEQ0JNUlhtaFlV
            TUQ1ZlltK1ludjhuVEcxMm1SbWxhRXJpd3owClNDTUR0Mm1tM3FxTm5NOEFaMVdG
            Lzc0b014NHlVYURaN3hLVDB2TEZFdjAKLS0tIEUrbk9BcVdpeXEyWFgzdkdYRG9O
            SkpTMHJGN3BtNFZxRm9xT0Jhc3VaQ1kKpn+yjBiBIJ7MOgJB4G+vlGtvOkkvi+hE
            ERWoHbiAWR3B64xPnSX4c2dqnZcxOAGC7uKQdwiZCrs/mp3yrUuWtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T12:10:33Z"
    mac: ENC[AES256_GCM,data:3G6jh4VuUagD04S0LuXkCrUql27x08cnMKZ5bds6yrHjkQE0CLowTYE6ZKqV0kpUIeMMX+pFJaBsNJm5iGnMoQgEy51krk1WU5bKWMKwqFi1BvnAGd0dPxfBJV/N4W5WaOSAPcxVInVua3pwIYqDCTCDzyd4grmG8vR1va8cb1A=,iv:Dbi7JAnlhjC7AYlxCSSB1xElY9u4jtNSNoYwNQy2Ktk=,tag:bwaLYoyxLkR1KCeD78i5lQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
