apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:39neqEW8DXEr6iFevwOnVj6R581DvwAxZMAp46a9vig057PnyVOxg9Qc9rHsfzzP7UpwPCyGq+nHY4xtEGOaRwm8Spz3iiA7ufh/Gyv+N6MOiQR1PckAKybzI3ehHrE/TFrGQeFFYBXCMct0JpxLHjT33ij+HiACOQ==,iv:Kq+JmeSGusPkiMfYhyK/kHF59CHpcm9+tNDngwr5d8E=,tag:aaa27hvXK0EeS4tLM7I/oA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVHBTamRIZWRwNmpsOUgv
            NlhkVlIyQWw3cFBRTTBzbGlHS20zQ0E4K25BCkd6N3Q3TWVnVXArQ1IwZ3RETm9M
            bktqMkMyTm5sM0lERWR4ZUYvSFJ6NDgKLS0tIEFiSEp3RWdyelo2dnk5UWlob3Q2
            em85aXNycGh5dFhLS3Y4dUFvUzFqYm8KdGQxruFHLClob4ebth/kZjcPn8jOlit/
            SSKHgfeomzpQA3conS6cog8Q0IUUaax8ZFLO2svRKTO4tdSPXtaUHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T16:01:11Z"
    mac: ENC[AES256_GCM,data:jYvKcpnJ14C25XQcUA5wswFXYrUOkiQqOg1i+i12Q7Nu9N4rg4dQsIwPskBG0FLBb9YEXoMBlYWGaXOXp/s7LuH6TsDMXpJCoKudqCwI6BunksQx22Uw6eqLn62Go3qba+r4+mth9Cx/33NP20dPc0fT7ysA1q+fVZ/IA8PTfPk=,iv:gF+RySfb7+N40fxuwKqcR6vq3XCeDW2dAuwKcqWZWEs=,tag:jMK4XdBFEnyJBa4TQuTevQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
