apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:NTgvf7s/XivJbVoCu7iRhjvXfdHZK9mvCYJaG6q1DgwnZwfd4J92QcvH9MrcPveK2A39CFQKqOomphhTx7TMbsZk3v0CshruFJmWuIUfx/TX2euH6FSzwnJR+D9whW24ZOMoiwVQYUJ9LKnOk72JjxhkMVFVHzwgsQ==,iv:WatO8iHPQP/odSiDj/GENa2O1W7r4LWSGRr8Zr607wI=,tag:Ddo9UrMfp1aXWJ1fDYVu2A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVWFudmZJS0NHZ20vUHRx
            eUtCVk9mNnhMaUdkblRyQmd3THJRWkpDTGgwCnVHcFR6Um5JV05vaGdlK1BLLzNG
            K3I5UFBMZHJsOHZjOWtmUExobEFKZ2MKLS0tIGh6Z0g4T1pCQ01iSmRoajdyYlAw
            WkFlL0I1aXB2aE9za0VsSW1yNVovNEkKvr/JuOPsXQaVLQLrwmch20WtMSdYskos
            5H5cDGAD/Jv0Dpg2QCypQo4t+ACO4KGVuXtPJz3I6PnQNWKUV64Vcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T16:17:39Z"
    mac: ENC[AES256_GCM,data:2wALmh3N3S2BYVk7k1CNzsa8Vk8P5EW5LIrKTAxvnqNn4uQwRes3goZitwlKVpvbjuDLXIgHjk5VnfJhjoyW5KQm9hGG9UhBhEbc3AEqr7Cj6aYKwov5G6bi7pLbQVLxqCz3hQbQH8Lwifn+qXgFaVWc9PqdWMMoyYCVqPlcZEE=,iv:Gbej1+DeOfTvfavv6X5YeuHh8dlcbOjoU/jB5yu+jAc=,tag:FhfxaZeV9TZs5IXrHt36VQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
