apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:9VU5WEfB0FhPCAlcpqsUW1R/20dITVZO7K6xiiiCnN+x/w0YAGey/yb4dhFMu2AWO/flrWzEF1ODQhzjkliLYRJBwGDfq2kTaXGm/YkZeuK0TZ6T0u+z7ukfjXeDEVIC9g7v7yoU0Z4WpvVTidPdDAfe/NAt9Ut7eA==,iv:KNhPJPmAN8fv2f8jDlqHipFlOBsFQl7sc/TugDcsKOM=,tag:svI4s920qYtErAPXUrRFaA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRDB2ZEc1L2Z1aFd6a0lN
            TUtjWGtRWjdJSU9QLzlybFdDRjRkVEgwbGpFCk9PZGdYZlg2NXhlYTdIUXp0MnhK
            T0hRblFwVGRNRVRrZm1KTGZ2SHI3NkUKLS0tIEhhNVlUZ2FPcERrTU5Xbk9adWsx
            MVN5K2hFblNta0xjS29UeWVNRFRKT0UKNqVce5Nh/ZHsh9iCOXxGCS3V4NNM+kSL
            Lyhus3AQUmr4DbzqW5n8cBMkFbwBi8CAe0Zw5DpjPn+N3gszFT5N5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T15:48:55Z"
    mac: ENC[AES256_GCM,data:43G99+tPsL8rOMn9kqinWERDrQImG3y6ma6OWMqQGnpMtp/17oGLLUH3l6nN7UocagKLU0e5byz6bBFhS66WEZTjscpx2GiUhb5qhh++SQWfBoNCeuwa88QnzcBxW+K1OjxVD4tZjnw/IcaaFVPNren2EdFvMoCLdeZ5V/VWCJA=,iv:HcwpWz9Fi1rqfDSTpPQzu+Pxf30nqkhAzlrLTx03RI8=,tag:Kh2ji350Gxhyv1DnHMZZDw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
