apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:2KfLevA0hynXeRL2hj4WyiwZedJqqqRPLogJIC5RtzhpwnqYZ4+2aCcEbT620oK838MrQY8naFhi+3TTCSc8ZwF5jbSBSYs1bNKDHT9evAylfjAR9QlKNBXL1Ii7NKK2Pc8YayRlge40Tv7N8bqIfoxBWq0Xu30BXg==,iv:n9MKjzN30CZxrMFUrm7xRaC6zpqUleA7XxtuaTUMIJ0=,tag:Hd5m4eFDO4Qikb4At1rpHQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMXFDb2VmanB0S0V4WWgv
            ZHBSVDVXSFc0MHdtM3VtVm9GeWxPcVAzdVVjCmpVaGhMeWc1ZFRNaVhZTW5ESlh2
            MjI5ODBpVzBRMDlocDc5TSswbDMyQmMKLS0tIFFOSUVjTjNHYUJzaXp4ZnM4dEp1
            Ky9KNjNIaXVtTVhncVJ1RUovYXQvUTQKQ3n2fHgA6/CwZpgL9jN7HwfPthP6rpR7
            NmAcXUlVvD5CuewPr3Ws4d4UeOu+ACJ1bgvrfl61Pce1gZO8ccEV4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T17:01:37Z"
    mac: ENC[AES256_GCM,data:62yyN4QwQ7Qnwgx0GdovirPbpDTZSrWlIGCJ3AjJk+qZEjY52NR/lBtcZmyuE3Aae7JuZs6OD8z/02UXhn7MNpZwiB1Np8gcQ3iheRqAQoUqzg0YDnA4b0HzFyuon7aPToK41AhA1w4zpYhZURNNHGrxNsu6tE+ygBhPsnZFMaI=,iv:hDQdPqKdq/96cF3QVvhtO4CnYkSn57s9uwv5z3mpBbI=,tag:HUGK/KwyOK7UXzOLpHdSwQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
