apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:lZWdfT3tYaIaOCKhlvzmlp1c4uesN5YGGDXbnzd9MHWpQepqDTbxyd0DIbp0G1jVLvF4izHYXoOdnLAHrOLyaQBUPh1OhV+GDDgNDB9rFDkOXf6T+4/azrRcDklmTk+l6PLH02bftb7cmwKAJVcYPXP+4+rJp+0khw==,iv:Y995qxCnS6awmYeURN0/QPNsiGMV5tYYtnNS+k2Fqic=,tag:zGdRDodFpazK/FKsAXHH0A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbEw1VG1VT3pKNWwxcVZS
            dDFwNXdHbUtwbnRCaVBOUmZOanZmZUdBN2pzCi81UWFVdGEvd1JUbzU1VTI5Uy9Z
            Z2ZIWHYyaWliUm56L0NpWDY3Mzl6TVEKLS0tIGphUE1tcldyTkFTYngzVlNEdFR5
            SjllS0dWQzNxK3VLQjJQWFdVK2RFWHcK5zsqZo1I0zfL4HFWgS6YaKVQ2heQ6ogp
            NJaxy+XUVE5lowlUbqelOh35pwIShCVmH58h+0bld9roFFBGZs/wJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T12:18:49Z"
    mac: ENC[AES256_GCM,data:ob15vsN9sKdnZQ8M+hA548YoOyM3be/HqERlMekaadfOgkCPQUEdig5q34sFIKQCoc7gB/15qaDkhv+zzalvd4VAaAZarER67DWQABjO/KFDGadnQDadLNjhjNANksqZ6wbxvVbmREFPaw8SHGuYOrxLkqtWI9v7Aj85hOCPhhE=,iv:7CG0SM96gmaIuSGNjSnx+bIQOUDHqk6/J/1xIIW1WW0=,tag:rPoilXCfhFxJmB4CQXaO4Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
