apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:XIAxV2vNou+bjgZNtsKcAK9rnKkgt4DylIMkHxpvh5aolnDZeMsEl674jZkb3vpg13bo6p6hgFV0yFM+qKz0Sqs0KcyC0QjCHeZ/zVLtynqeP2/KUe+gtrveDvBN,iv:LcJpEk7njpK23/BLNWmp4N2SDd+nKeIIVj/UN6qGfCw=,tag:Zy3ldWMVG/KhpiVq1XE6+w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ0JNWlRPNkU5WFMzNGEz
            YkxSRC9jUlA3ZmIyL2ZwZyt5c2x5SzFLdWpjCkF3SUhqZm80MTlKMkVTSk1qUEI4
            L1UyZTJDZHJFUVhJNm5ZbGNjSHZFMVUKLS0tIGhFeEx0NDg3c0doZlZwd0ZzL3Vr
            WHBXQmQzUHMzdUxNWjYzR2dobnlJWFUKVgyY/SNY+Hg562NU7Nn/ZTiUYRZR3Nfh
            f1jwRubycQtvrjTikhLnCB574cvgqmjrojLP/9JRSxgkZk1FoBoPAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T23:11:31Z"
    mac: ENC[AES256_GCM,data:1fpvHMXrI4BkglzXn7LRUpG1L3crDxbRvzyTnG0jfi9IF5CJDvsXVuAGejMEYi7pai+N8ypYzVP+rD1QdVcjSU0uECcBk5Lmbv29vmDnDPw52J+IXqrT6nyokZ480fwi0hcqyZ8/1lfACPNjx0L8W2bb92DxCkYaQMkigXGvo3E=,iv:MWfXgyMGGb/AXm3NNPOoF0ppvkzoV0bUyHlzPR4wmZo=,tag:UIolOnLGJWB6tBFe6nP/1w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
