apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+Q5PpnniMuP3I1vIE7JtpflKr+0lArO5XEguFcqt2me2/WE1OibafF4rqcezru7ZhZ85daIAJAz6cNg7tVt2YAF96tlXNguCXOf5FswpVyFc+pyPl6UbheN6mLbS,iv:V7reuu7EIP9GLv1lkGuTPRJsceJEBxQAyytGPfY39UA=,tag:mIqrM/ZKQdw7JgsV3S7O6w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZTIxRTQ5Zmx3Mk90YXhX
            S3JyNUpYSHJPeXVBUXVtNnprU2VDYUpIbGs4CllJcUV0cDVvUk9zS24rWkFlWEhQ
            eGVtYWxscDg4cmFHVVJUTjJ3azdnRjAKLS0tIG1BL2s0TzY3ZXRkYXFWQjZ3WU5Y
            V1BUdG95TnZWak9hR2NOSDBERlB1TVkK9ha7wK4lwZECLk3c+56LoOcfZzLVCt8Q
            I2Op+CJfv3RttyKEAav7Tszl2L8n2JLQ8gxK9k0TrVegv1mxGMWPVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T12:49:40Z"
    mac: ENC[AES256_GCM,data:TsO2OqnO2V2CG10l4RCi6jskc2FA0Q99dWpHWVj8e5rvV0vd0cpCX2voMW+BUMc/V3hSs3s/kazrzDig/ZydzSb/m4puq1e5uWMtEzQSs/QcflZ/Di43EEoGtRZgxoySjN6hJTcsWOxwgtDdP97c2bkxMqw0t446nm2ZcbCVoCc=,iv:EQzv+8xhMABGHqTVsctx5alUwGdydyZ+H1i6qyaK5K8=,tag:IqkxvITn9pioI6MZuLObyw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
