apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:D9dKohFOhuXMfI+hE/9TlKLNnjq0UkOC1SeoD0aEv6XgxzblNJnfyL4ZvAZXftvF+y+AjtCl3xXnr/mmR9pRwJ1mmYo4YEPiUyx76EKFw9e1AA+OHSl6U8WsDgA2,iv:s3h9nyLmvlSvyKhEjvJw4M5XQwsnBL08WRSN5Wc8vQg=,tag:JTxqYISg0u4ctkaZxrY1UQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ3BHZWIzN1RwTG1mcFZh
            WDBuM3pYUTVDb00vTzhXQUhjMXkxUjg4Z1dJCmE2UFUvSi9zUlo2VklaSUs4Tklz
            RVlWVEd5VEMzVms1dUZwMENRRUtCODgKLS0tIEZJMFlISDVzNldGSmVGdXJNUExz
            emxrZlpDajVOdm1URlllU1l1dVlHbWMKw4xqe1cpAia3J6f/x17wVK0XtQ5/Sb/Q
            fT/pYdBGzHUJmLfhsVpCD00iumwD2XjReac9EjupfR6hf0y5UslqEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T14:49:01Z"
    mac: ENC[AES256_GCM,data:68MkggBDxAZdR/OYsJGB9TfscUbX9yaMRQT/dAPH6SrnmD07d6D59t2/FEoSf9gV0bKTXM0Dy/YVMUT9/dLVq97Zh0ZK45YkHTmNTB/eYk/YYhIn5YjAzkkNLseeTejoOrWXkOvNE9mVtWG0lX8MGOEG67rrm5kx186jE0isqOo=,iv:tZceidIj+Uq+u5eIDt15jYEDHf/uoRlH8zVlSXANnXk=,tag:mV5DrwpcLSybgv/FUscNaA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
