apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:qwk9BjWYv7jN3/vu5Pu+DdPcUKUSLrn/6u1wf/F6jHjbCdPkR61DXNNA6lB3eHNWIRSrwoJkDHG6fQSevB6BAduGxC6MzcsWLHdlbgAzqINYZ3CYHt4S4aZmduv+,iv:pmN9lB0X3BZFWu5XjdQkI2+xVnUQbuCSaqHSYiEmJHQ=,tag:eirhmROW81ENfy8SWbdRZA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWmlDeFZBcjAxZXhpWk9u
            Nk8rbDFUc0FURlBKQ2lQNWRhbDJ3Nklqd2xjCkE4djhXUkRBSXFPUWozbWxKbHd5
            YUs3M1ZKbTdoRUFaemtNRGpjaTl3OTQKLS0tIERvTXUyUFpYbTliWUJtTkNhNUJL
            T1FoTEZyS1MzQnQ3Vk5yZS9NSmxuNncKoeDPRM09XHkiA9a20GnSYHBt/PgeZw3d
            +oytW9BTJOa/wI9cLZGGaLzxK6y+UwgQYdR+mlqfGNgtLJJCfQk3pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T17:32:36Z"
    mac: ENC[AES256_GCM,data:U+SO38SRtSekhyd9p9DflZ9yVfLrK0FwJMHCc9tJbboD+ChlXWuXcR6h+9nOhT3cpPYmPgtTT8Za1RJe6pusVx3E3+b40PodFwI2cHwzWMQETkX841wVSCjjNEt84yL7bqCKxEDRemGJ0tpruXLg9yylgfp91pEob111NxvDigo=,iv:Uu7fIfAXV5RW4gfDUhQP6N0SiDD4PROuulBX4zcl/RM=,tag:85eTwtea/hkXKnucUdQlyw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
