apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:QToebptYb5NgpbvIIf/OE5ZvBeCizatLv4pHd5notKoJL6a58JmkQ/n5a52DjO9ZgEiewKYJv6LpQ7PVi0RBKtLJCOEciYRkSQMofuDjaVucpBQKyLUseilgdF2J,iv:eWclx4AFHgbby1cH5PVxxoQ2xAFK0AMzRuHYNbB2CTQ=,tag:qaIugwp5JkIdiQmkVFaPCw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeEIxN2xXa0htOHdJU1My
            dncwbldDb0hCYzZtdUZ4dUlySkZocm5QTDFBClVIUnRvek15YXFnM3pzcDZZV1dl
            MTRacUFzRTluQy9La1Ywdmh4eWhuU1EKLS0tIG01STl4Zm9VWEpXRGpyR3hvUUxm
            R1VHMWp2c05GRlhHUXk3TExWYWNjUEEKvfxZlvdKdoTnZ0U+Iz0C0YzHAttWciVa
            0STQ7OUWc3CrC1suulJJuosOv08iHtH0VKtLA3w2Kmr1qCCv9+W9oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T17:58:12Z"
    mac: ENC[AES256_GCM,data:73YTlLp7Vpyojs/WFJZzC9RxBHyL6STzty4bT/7DoAyWkbI9BbWrEFAyipazXFybZ6eRh2ANz0ybzNlMzCgB2LggFG9Zd6+MhJ1Ow6G4M1oChP0z30kEe8bx9CBqjRwjFzw9+DEy73pl2RvIiWBVI1MhatwE+lqaDxtif8sWjac=,iv:hSFucI/SVUiRaw9B31jeRuBdjDX2I1xYN0qiUpEd8KU=,tag:lX/GlZY/WzAM6qXomSyZ0A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
