apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ahBGgcoDWRjA0filejsDBpuRhoMH9v+w5796ZrmBOJnoQfitlSGYW0L+Hc9Ndf0PfXrgAyW5+QgfF8qgIqcw1MG9MvCEZLBeOBootYqndVxqUxL4zBL0Vllbz1cK,iv:o42ovS6JPGBCIyz8WNBSSo4ztKKaSW7mUCDMduX7D44=,tag:Y8Xh+55fIfP5C/Ce6REdTw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArU3lRZHdzTU1jOGgyRXFj
            bUFkVlNabHYreXdLWlI1MXJ2UWtWTU55VXhNCm5WbkVMRjYyU0NNR0RlTmEzeVRv
            MlVEYjhTV2ZjS25OZkhPd1hYTXQ1aWsKLS0tIGRqVkYweERielJja2pYT01VaFQx
            RmJ3UHl6N2VDdTk1VHhKUXIvem5qbU0Kp28j3GD5ggYqI506Kr5EiY59m+NrmQkI
            HnRZNmZMIGv9iCKXfDxqiO8NcP2CZnA1Ysa59dl/rmmVBy7WBwnxEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T20:40:31Z"
    mac: ENC[AES256_GCM,data:5j3LfU+k21cb/P2Rhzt0hhsTST/VLffIh2scoInkJYS9Rwoumm+zo6GdF02QZ+rtTVO4kqL6LXruxSvJt7gBxw/WSW9p47POC2ae7kSq26X7W0MP7QEHjw+gKUT0WkFqy8O+oCblsC7Nf8v6Bj1ib03yyPnA8KIJCs5plL8roN4=,iv:Xlkogk/6FWue9bS93eVnAKhGZ1vgt3qA3xnidZYc1HQ=,tag:nzOx9yOK+N6YMDWtKohPpw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
