apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:sWG3hG6SA7z2FFXo/yEnwXzUeND19Ws5k6dgNdn0qgAYSFERiYLMnP5s3oyGja/HlqlaKTaiq72R+ZfgDVoJL6ZJDcod4vEjOuudr+neaQiSlQHxcxhUUsojlkDN,iv:0eoFVVymjigK26fu7kNtfuwBQ1b1QVIDneK+RdJV9yg=,tag:E3ckYHnI0BsZaTbidb7j4g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZjR0dStoZllHVTVNYXJs
            elB4bUlwb0FFN2hVOXJwRlhHbit5bitBUzF3CjRvU0dJQzd5eDArVWJCVU15dWxR
            WVRWeEoxRVBHaFd3M2ZNekpaclNtcTgKLS0tICtvclJMbUhqR2pNeTJadnI4Q0Nn
            bGI3MzBqU2hVdzVnMThadEUxZ1dzT2MKMrH10wDdAeGBMdAwzFuzwymGGv1XJwjk
            QW8/n0yrUBJy/OOtYZj758vI57ck6Djg/YyN/UmujSnWJQP0xLBJfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T12:49:32Z"
    mac: ENC[AES256_GCM,data:iKDZlueJYAZjIf5LSUIi6NZgp0VLDn0F0LIOiInKkHH5p/Y5HMmOXGGO+RXQKwuJjNjRcjJFQ8cinoU6Z9zK4yH6mYD9uwreNR153zFki9dA2NtL5eB2tMNZCwhG5wB8gf9Da8J7lBk53tz9Xzc2D9SDnRyisFUF93PCyyB4kUs=,iv:5drLzipmbdgSXOfD9t6OOYQj9TxBAmcF7q9WO8ReoLk=,tag:xSO9rADisjygFN0wzxp/9A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
