apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:QEV+sEIhpAahzq7GMODQ44Tlle/cZV9fKCgA5STsJV8/6on/3+VB/OHQUe06kAwdZyt+Px92kHdD5bSwClvnr8oEaeVu/w/vK5fYTNIS+LVst4D96Jz2x7a166DB,iv:sT2VL1kRhvnZgfNK8HBa36PYBews2Y1FYFA6Cpj1U/M=,tag:WLYzAFDIJU3qywa/AowgEQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxblpsckVoWmFma01PZzA4
            emdyMWVQbndoaVRoVjZPWk1QVEJGb3FLRmpnCno0ZFltSW1TWnU2bFNmTW9WM1Vh
            MU8ybHp0L2xtYXF4NzZCWGo4d2hod1EKLS0tIDRKNnBUR3FIbDRMR0lUWXp0MUxw
            UDRianVTR2dyaHVJb3hyMk0xVitZR1EK1DZ8J4e8si71eXQi4C8HYtKpN81f082M
            PN0QLReW3hrtt1aSM+AuJrxPScqMPRYOCN8V5C2ngpeHLCmEIPMM2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T14:40:30Z"
    mac: ENC[AES256_GCM,data:miTZH2Qz5s+0ecv7tJxxouesBykG/jLLIfwWxnCZUmpkysgglxM7ghU9wDpuIg8buG9op9O9MCtAFLNZ5ncCpHb5ianzfpad9vI1Tbs9uw7F818RVgomwNSVub+rEcd9pRHANDJlfDkM4G1+UFlkDT7npN6rI59AyiIXmQDElu0=,iv:tAb+LXVMPesNMxrqc4/AtOEgyEMiAlah/U8xEcrmBV0=,tag:3TpQz0xacAp8KIHWrMTE0A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
