apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:9//AMbGOrC8oqMHukOwdSx1Ak9vYIpvsTY4HULApwa5PdegdfHsWUzyfYt7Vxb2vwfO7rHKIKnbqOlhix8lXpsRUmXFHbDTN0LudDguKpfHmSxcWFXaMfye1xyKF,iv:tiuh4+lCOcW39hlgm9J7HJ0Z/2z8ZyyLETKMdjiD8TI=,tag:TTffwzQfj4+ez8S2rn7RbA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbXFOVHNmVkJLMDU1bS96
            azNwSzFYM1NxSFQzUjBtQTVkd3k1STVqbm40Cng4eXF3bzRDNHA5Z3dQNHNwT21E
            WFZnMVBVd00yMDVtazlzd0xvVVBxZU0KLS0tIGRKK3g3V2lEUSt1T1hsZEVRNWRw
            cGR4c1RIbTA5SDU5MjcyRDZJdG0vUVEKTaYHumGQ8AkNPdqmwaTNvMErO2j72Q+L
            PUDSmXleDIVzVCktURXEnUQZx6upn/VdM4RoOykzPi1JedOAhvsOwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T22:52:52Z"
    mac: ENC[AES256_GCM,data:WtV42MqQ9RwvpTcMD9FKNs6rRfBIeyMEDss9/kM8Gi3rGiYkadUvZ36MkABnvUoJQ6V1dWeehKZgZX8Bh7T6XYedOaYpzh34K4eKQkesN1MT4UR+NwhI8iQVAz1XFfVEnVrTZxrmgxkXHS5Wf1g1Cyg+HOWGifhPi7aE0LCKAOM=,iv:IVWz2E9v/GZ6kSUjfDr9Zl8FvzoqV50wmtp7K1wI4jE=,tag:ZKCLThflOz/QcqxDloDOFg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
