apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:mdKA2q/lRp3ekSfRylZGlEmBXZhXRiboHYnbQg/5GN1t62ReFwcg3bSzXbmkEP7vYVEG225Hsu9HUZHSc4N90dxf/PMAzBuu3nOWBgcIRG6vBdrbBuPQuzJ76P7I,iv:zqLL8p0MHiCoLExOBGas2cxXnjvJMvMkAdDiOYDa3cw=,tag:MG9+pVcTCuWtKze3twCprg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOUIwNFQ0V2RNbHl2OXlI
            blM1Tmp6cEVtdlpwQzBvWFJJcGZUTThsZTNVCitYRjN4OEJiUTk3d091c0hvN0NI
            ejFFamFYMklSSWF3bHE5VVdsc1ExK2cKLS0tIGRGT3dvQytzTnduc1Rwd3d1VkVx
            d0xFMHBLOUU4dkwzaHl3MDhRZzg3REEKKM0gfdmdc3cJQnemCSrcnsAsfXWUR7/H
            ayMIquK+BfMANJbNkD01gNVXWrrkUPOpXw/xgxaLJGoe1aZQRT+k0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T16:40:46Z"
    mac: ENC[AES256_GCM,data:dyVVc8i2aGXpmcPzh8xSRTdamEqDIX5zkyi9aqKiIy/r8G7UlX6kCFI+LBc4Bp8phDhG5cOEekdKVW9xF7H3o5DXe4taek3kTkqDdJJPp0hj4WpTY1mmg5BzRlWdKIyl0SDcKNXQcGNjOWmLYf9U4G8Z0bU/7PP3alwkVbLRFMY=,iv:TDhpb4nqQX9CNJs+Bp64/36j0gZKSue9Wcef0QKMXts=,tag:rCOU1N4XMPrjL0UnbUEUew==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
