apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: exporter-fritz
  namespace: exporter-fritz
spec:
  interval: 5m
  chart:
    spec:
      chart: avm-exporter
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    portal:
      open:
        enabled: false
    exporter:
      exporter_port: 9787
      devices:
      - name: Fritz!Box 7590 Router
        hostname: '${FRITZBOX_IP}'
        username: '${FRITZ_USER}'
        password: '${FRITZ_PASSWORD}'
      - name: Fritz!Box 7590 Repeater
        hostname: '${REPEATER_IP}'
        username: '${FRITZ_USER}'
        password: '${FRITZ_PASSWORD}'
      - name: Fritz!Box 6690 Cable
        hostname: '${CONFIG_ULM_IP}'
        username: '${FRITZ_USER}'
        password: '${FRITZ_PASSWORD}'
