apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+chRxmYtNAkgGwr1oyjvFSpP9x/QHQbDmm7icBHzuvtoapxIpXzHFSv/dW5MrMocdRgDaM5ErcXL9lmbeXadyw7mcxZy1Pzf+F9reI8WNpKV5lgLtBHCbqJo/TfLAmaJ37BYzI2P3iMeIa6AnsAcmBSD5qMLdcBrsfDrJ8Jdq5H0+GRjQfvSyhq+U/g0CEYFLywbdgFiBjrPZkkQyta3GdJo86DlDoagGNjCY5F1ncPZTw8q+F9WraUqVP1CEmgNl0UI02jfZ8MiLjlsyFg1CXVrPQhUt4xev0xUoVPKaodIf7M/wmZc0WCXEikupR79MZw663yg3nXAeJJlGuurTYVv6bJHKNutuhRTWXmdKn1Tj2iMhhbOXFDMbAraUo64,iv:XaOcooh3MYVe7fhIecplQOYH8FP6AcWLbkrwMp1bBEw=,tag:FmooLskGcdKRdV1CR5ipbQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:8zfTzO+Pe4mHoWjfL7gnvgpTxeZxyV9yHxft4wFsjJ3ceuqQ+OCzUDTHOt7s9JWZgcfscQKWkuSfxUNL+nA6YLp60B3clmGwp4DIuilAMYE8c2PK6rwCu/7Zd8m7evyQcVp28o30YV8iJwoQS4GPHjkkqrVgbc2sPHUBFeJWMVRHTJ5mlrUm8xByBiZAFaM7JRiTdAXXtEYTfW3gU+xDHWpDkYiRrz2U4MTrcOzHXmbGXOWhJePnFYkL8ytC2wi/VUq+b9RXCibkST/EqQ==,iv:tiUG2t+Gchk6P7wMdi7eotfsADH1Oo/riKp3CaaRe4I=,tag://gL83EOQTwISMFaUpJ+WQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:VChipGi2tO6eJnM/IZHd8px59Ntmp5wCBqZVUy/fbZc3O91qg7zvhDpCt+PGEgXfkQfRvm78uZ4vKkMi4BDgLj3jo9nl0zugNEBEfMujl2fCKvjp2u45X16mCtkRe8TLsPVlRnQuU/wVXaisj0/507PZpW4E3H+UZmu4rxs7VTXLPZYOgACin3hp/yGYAfHn4olOROw3fATuUDny17b7T50ARfKGus47ZKG+,iv:73lTPBBCIpaQRJrj9N/AWYC78VQNOStTk4dWPULco5o=,tag:n0LD8u9X+yDOt8H/hHM5hw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Nzl3a1RMcVJCRHVOdlEv
            TlFBU3YvdFREZFR0LzBPazhqcmIxZXZCMjBrClVyQ3RFb0N4bG15QS9kaktEaEJB
            aVRnUWtmS3VCZkZWNE9mY2RhZ2ZxencKLS0tIGZjYTd5elBxYkNEYXBkUlhoME9S
            aGIyTXppZnZ5eDROQ0kzejlZdWpPSEkKghQ9Ct+L38Rha0juzkhj/jctmZSieJ5I
            Aj0mcbSGxGHJBPwAMpKEG1SpVyMzKWbUkwIOggTl0V0BGS30IusQhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T14:49:01Z"
    mac: ENC[AES256_GCM,data:pB7QclVwbism8GvRJz5Hx3zUDhAJRjqm5ZLkj6DMJcKNW+PA5BSUBgf7VEA2zmOr8IqbPVjV7habw4/rSg8DufpHBFBaZ1ZG2Q2Uy8j5F1A19/7K5z93O6ZK4fqGp7pZhsYKp3iDZhXuUahYUZ8XZJyMhuKN9uVBS1K4rFG3He4=,iv:eCEcRIZKQHle2dyNPa4/mEHaCR2sgBx0/y/qe63ZY5s=,tag:LEUj9/AKJdVDuUchSgCNpw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
