apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Yf1g8Z3xNhV5Vcn++SHgZSialI606wHOaYJFkOGu3t4hEnMkz95g1raUTnNwt2ENC/tpIkdsJlAJCW+6iG32OHD6nrMpdVghn6yXeW4QAIyZXhkMpEDX0sO+JOMlh+Z6CTSdA9zTuqciZ8WqJRDM095W9ZtlXd5vvvSzP7ea5Og5dUbbE9LU/jDod76gYfb/A4Lg8qEBgrtcy9p7tPzFrlRGiaZwkfnEkNnYky5GWxYDQ3TMR7los4VG/bU00B8pyNGiwcaPupNu2mpWTISNFHreLIpZ8Vhj6wBHvQkx2E4hp8nJXtt25tl1H6SYWcpws7Q60UkE28EPd8Ov3cYD1+n86RAMgJkCAg+Auq1Bo5jyC0L+sLN5RF4MCOXKObBa,iv:9Dt7fkxCP1+b7LvWH9HcYRX2c9Uh+kre3XXlwBF5WyQ=,tag:tD/Wr1R4AUsxnXTMCMg+Vw==,type:str]
    identity.pub: ENC[AES256_GCM,data:dqelmASyAKQOIzLAmld2Ix+p4n7ALGXcDqQGSyplFdEgpq6hTprVhJRY1ld7wKhz14cktHNkLKHOIO7bxfTpYhk3quMvso/SHkn9cxOppG1GyV9gApP9HSajk9o5xJdv+5FGDeAiB+BW/219FNkPg69AISO9WRo+XUUMOtui5gRS7dFI8CIQyjly1kri6VdDouw4+LvwnSCi32bkGK4osZHYoXMjG9CBe/vN0QPm+aj23VKI/TirGV9j2djlf6q4Nq+rdNN01tETUUeaTA==,iv:4MByQ9Byb1OiIvA4r8tNHv8Q1ecnGm+b6K+lJ2fbgIc=,tag:4aVxevSmA+Fm6PuFLV2ZNg==,type:str]
    known_hosts: ENC[AES256_GCM,data:fiihZFEiYX/yjAnyYIEKSLKQ+c5SKuV/TaJDPTTjw2ixGinAvwyO8CHAW0SqvDS/6bMA7fadVSA/zpOOoMCVV7PrroqGNZbxkiYyksr0S8W6DnvUfork4NwG/k7MJgq9RxrUKwECcLfqr8F7mx/8NYfsMe1aWWvxeq8m7S+50stWz7kH6LnxDoWlp12MlCGfiCPGLLWGs2mQNkxOShUQbgS/XLJB1yv0GLqU,iv:96cRGvbRmGiLSVH63/wSgjJH0JmUcIK0QYg36Y5c71M=,tag:nmXE2/6xllarNj+L+Cgl5w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTXNCUXdqZ0xId2FwVXIr
            aVp0NUJsWFo3TEtqc2QwRUxRZ3JYaU9YbFcwCkVpMit0QmtwRlZUZHpSVXpKSCtt
            ZHR0Q21RQ2xtWE9tV3Q5WWhrbjI4SDAKLS0tIHg0T2tYVTR2WTZ2VWpmWUpqL1lE
            Z2VKbW4vQWt6QWJMcmZITENIZzJDQTAKIRftdpI1G+kTOyPsihGRM8wffwOI2i2c
            4k2pjw8gDKx28L3oaxq7BNEMtQCpAwr1hUQ0/1WA57ZuAQaLrB/dwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T14:39:19Z"
    mac: ENC[AES256_GCM,data:UnofnxqKo9O+tsnuM44YO+mPyxi+2Up9j3h19T/PG/hwwLUnWMQlVnecoRYC8l37aKgoOfzXeI0Ksr45Ev6XfEhblwNirAhSSkk12kt9RKLnmFBGART4tBLWSviE+UCLw57jG/f+C54e2qDV6XY1x3obDnbf4wXLlyl+M2h1FaY=,iv:hfmjipUFDko4kmoKSZBku3tnPLRmFgEuA9NNqAzELPU=,tag:RSVO2ixyU54b97q0FbIRSg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
