apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WWQp+OgDZvvLYjf+96EhvUsVSm+hUtPsp8agkIjyMlfTwxYmgLNwPQTDuq6GxWsAKuIPqI8pWk77LHfXriU3NWAOaBhBNZKFr/I3wuTgQgbq6yCvt0Ht4t3KUSiUP6VkNlXE1QvR45xIM6mZb9/26pnFwj36kvKlfx5fiw3pS4nXRo96HZc1FwBnBLLluj27ZtfsbxwhVyUsYjyYR5HY797+Csre+n6qgc6H71udFF24+2DXZP93VgTA3DKT9OkRBr5YxpKUqDzKgDFQTACmu1Ejp39gIhWmsrsonU7ccBMH+iI7nJQWaiuJR7fQVyyLUFcKq33eIgwYveH8waajPLvzZhMKJpjy/6QRHkT/revx3WcKq261AuoF5c8tY+7k,iv:Q/g5+D0V6tO0mscc1QUsqC8SQkwj3T66nIKFB7M2ObM=,tag:YPxkuG03EZnUBKUDa6DXkg==,type:str]
    identity.pub: ENC[AES256_GCM,data:PFGJVWqZcx+if8mtZZzCOGFp5D9N0c+U0VLE/2p4vJkJ5RlE2qAEjZFJJVdAsUkazMqW+xAI3u9GWgkqpqQt9Yxh+gxRM9dJ8Sy4u/Mosu+JM74mDWz2e5yr/u8uVKyZHKVCPWLE7ICm/gcjCWLdzJyqvk3myEcKzSaFICVV9qpPljlM1gtDykYHQUd2h/Wsn7YIv2bWs4JGEuUAft17zTYLp4aq1gy5kUdvBTxMXjHOrKvmtqsLxrf+djueOn9JHFVom4rWbLiW0YoR6Q==,iv:8vv+AQdxqYPgvBhIjBhjW5FsKwJQa4pTe1PwwvBG+8o=,tag:gl6hYD2XsLmYW2ZzcJcdWQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Gp7/h01EdSFyYkq0Ep/c2gR9auShhUiy6KMFeTv4+uDuAPqW9920bnbg5K5dFadLUS7+4cm9phmtfY9oj9v6Y6MNMhQB0ZNvHwzdB6ri9OUZot/+KTHasqR2JdIm2IpRGJ649ahTkY7FCd+DHHZUmoE1/hyGqH+G+NZiiH7URrVhrEAdlZprDvdeM9l1z3mmrD4BTiyupg0AGuJ10N9qGaA65pAnAGjuNtG2,iv:npwVwSMpHsJ+98mVXCEm/S0aT5j2rBx48fMJdkGdjyg=,tag:8nnHEQG5fD/FD1EQwQ5NJQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXR3lrQVNZVkpncEdYNVNQ
            YXg0M2FLZzZnRGc4cEUzMFJxTUh1cmdmbGxFCkpLd3Nzc0QybzN6MndwdDdqUXpG
            S0QzU0hjMGprUldjdFBZRlZZUm9mdTgKLS0tIE1veG5iNTN0MkpYdk02UkxzRVdp
            NVpkY2ZURWNsb3RadTVTWFZPWVkrdWcKf5iYvdGzfyGGJcLnEZXWK8xmLN7Q1EJo
            0zsivU+DAEq6ssiENxQdmagMj02Si9vhDyyC+AEs+gGucDv18voGqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T12:18:49Z"
    mac: ENC[AES256_GCM,data:CdpWw5wclajj5R5069eP9WFDpt29dU2cH2b+epyE0CCwwMRkguP8zZyIdPLX6Vs6XsBzfNd1xaAlUfbAhV39JaAHtq8RHUYC4sDX5AY16zP4MSfE80dxGHnkleCl830TZMP/Mq3zBnas/F+H2zdOh9n8QIJXpASdwPtSZ5w+trU=,iv:cEWA3j8TbbvAt26+xbbNawAXaGBMzJsx83n4OBVTjnQ=,tag:nwjiS5iNoCGv3gzRw9Mnlg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
