apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:cBlamLb1qjLV4Kuaks8S7BNjegSD0xMNw7xT1uMXGezApJU8CJcAu9+HJgMhMBEcPvtTxl9Bbp2B3VM8S5BFyqY4Z/XXW+ew46+h6+ga3WAPcIlPx0DhUcld9NZ7ncQikHWdYteg2tjxMnXcQ8UMO1BH1rbOKG1lCOQY6s4tmp2W349ijYkW/z6c2TmgV5nDvZ0MQ1rMr2D8GknACSaTklFevKor9F+kGXFXrBDzHsYzaBWevLc35ApgQAENlgs2/lrmNMjUN3aM3cXLv9AZyESLAWsfAFMUvI4E3VmqutX1Yi3fp50Rmb7CG76HRO7CJVaJ+HvYsFUpc9W/euArSOd6kIzy/rRqQxxXzzE1plwfPADoBI8/nnZNO9RcI3Ot,iv:t3464D0LKUU3e5PBOnakGs1SXBxG1CeFCajSBSVkz9U=,tag:LxlN3pMHFqiH+8jGa2ZhTA==,type:str]
    identity.pub: ENC[AES256_GCM,data:uyv0kkioJgVB8cz3F+MdzbG30Z3Czkq9OB8PfY7xlAe19lj1X39rKBbc23a3MOlRrk2L57AfaPDYcNwT/4oWzPlaIwufI5Nyf7NlHKb2ZUcfyO2jHJN23h5UaCywvpql9JKslBUkUAdpCj+kv95/DmF+J4us+nATz2NhahXImlKKsyqOYWum7YEirZQaGHzW5JgWIyWJt8LhBslNZDUHB3/dFdAQyVXSkk+QXqs9EwFfUSSc4EdDVYE74n3wmDlcsC7Tmj5Z+zM6n5LyeA==,iv:8OpP0WqGEm0W4eksog9hCRPsqYFqZfPCVnqDh04cJSI=,tag:/26MKOeR2Ad2/fGEiuIY6w==,type:str]
    known_hosts: ENC[AES256_GCM,data:D9cug5Nc4GCjPDGCEyEnW9zN2DYxsEK6JTB2FkitbmFf2qa1hBeJMTOGa/D8xutngjyV3CgY5NRq8ivnqN3pcOJ4qDF1A8nzRYNqQyNSpu4TjnucnCXnFrKBp+z/CUZNYAyA9YbCCVC9+Kbd1wINgjj1ePIDTg//1xSMsKq4CZb/HerYFMwKQKOD3e0e756wRClt7d5sONaFLBEVHyO1hkwpb+h1lt+pDC48,iv:W1dBAUhrFHxWVfP+BEvc+eE9Bmp0NWnAjVvnACz0FYc=,tag:LJS4NpTo5htecyhhxTlJbw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUUtPNk1jbzNTc0hqSTF2
            NC9laVVTVHpIMUU5LzYzY1RvUHJ4VGQ5K2wwCkkxait2T3JhVnlSNk5iMVQwTGha
            TFdkMVdQQ0RsQ0wrTGpad3dhdnhsb1kKLS0tIHpjVDYvbmtRcHQzZXNUbExYR2pl
            dE55SlRaSXlBdzE3SEtmWG9haXpCR2MKj63GujH5bLXBq091AcJ5XjQMHPFxSjdx
            dRPE5G8IG+zJLNwCJhEzxjV+fJhQjg78PzPLn6Jeps3Iu96ZGJ6Y7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T22:52:52Z"
    mac: ENC[AES256_GCM,data:6xAmQP3PxV9MIh1vSpwmpVRGTogGZAZTwVewJwK1Tb2ujqU5inqmtdYjeRUWI4uRQpVE4JYxelTGnJELymw0N7sek100atb8Yyzxz0L+iAt54hZ9h+k2ooruSRFN/Fc4LlcltEVnDyt7DeC9CjLnnJieWCS1DmSb3AIww3gIxIY=,iv:NivyUsMvatd0dzk5Z8pHMB6vZ65NpzqAa/912/Ic4qc=,tag:vvJSi23Se5yS9fUpk5lLNg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
