apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:AbMpmY+pg8jpm4OSeCEUcNmoDmdkj80oQo7H0aIUAk9KTZUjrLFNSPVfincEtQdAMPO2PWG3aykMogAwBPjC/6NW+Gj+1XCATQai8mueF1oy4ovqcRTQNfAyWt7/RuWoN1MsKKahNbWVVwP2TsVo6C9i+mqO7HfigL1hCsxEubH24gstSfAHJLClVKooPfCcMAyfvfxdA/54ry69zDLOi6/P3OrE/yYjak2zWqTq6ZSQQSCz/PayDeI3WjGbIMNShyoAfWEjgBFNhDPh9bppdpJR6jf37pitmihVtI54WiltE2y6pUdWR5UruKqJ/KL7zQnku1vICJSeragGWtFlWnEVRmNHWevg9Svf0WZQ9D8zfSr5jwaM+7NwvMei8PBv,iv:TtD3PElsOIxz8PX3N2ZS61r8wvnmjZatqHbwMZ88p7E=,tag:InxCT6pThFtk9khSbTZOpg==,type:str]
    identity.pub: ENC[AES256_GCM,data:LiQiDY0YcevOvyke3VEDVe6kMOXVUSiPkqjDhqmXnSE9ai4OasN6de8KUt1Csb3arY/CvLd8VLjwD1vTN3p+HN+CNH3CNe3pPZLmS22dI5akmr6xmlAeOilsilChNofdetxfeOfveHKJbtys7g74fmD8TH1yZLuELOplSLlgOM1YWbLHhYh1jqP7vL4WsdsDqi91bTpYTRG16AsId0lM5R1FO8STzFhSfajBdP+ZwuXG8sHQmW3CvYDWQB+Uhm4Tl+ttNT7xEFA/LOEGig==,iv:EN0dq3Fu/s38vpogQkXnXsimNK5KMkpQ61cbXwl/hus=,tag:c3huGkaZ+lZBsy3L1q4aag==,type:str]
    known_hosts: ENC[AES256_GCM,data:d6A5m4pklbVUwVG3krmY9pU4BaSd3KZ2sdA/UIMhUma8V9k/hADURbLClHfmZzMs1uGIP+rQRBm+MopSFU5wOq7c/7yesGAXAksz7BNIrnVmcqORD0Y4VyFHc7y/CQ4GDFK1ORrMJkzz3ofUWCGQ7XhXwKgFwYlir7mBelYv34ifckt1BI69nBDb1QBg6z6Vv8qiLK0MOM2y7DaSAt9GlqTVt/zMukeYsKOG,iv:jDH0jue6xnpi+ugvfI5um8tzonHr/5Vy8QGOPFIToy8=,tag:vZcjWU9jsS+23Q0oV36GXA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeXdxRnp4VFYyZHliUGo3
            TXNnT0FqMDd5d3lGTVVhUWF0V3p0a1lxZEQwCmdFRlF6Q0lOYnJpQjhnNzYwUnNH
            KzFoNWRncG9SZ1FVdUNVZjRUUVNRczAKLS0tIEhkVGoxY1FRQnczc3UrWGhlbkpE
            SEFzMlQ3YjBZTlhYRFFBK01uMTFRalUKxM33Vinz5B51ChSD5Fjpb6mW356XHT8r
            d51oSGVqwg+RQj7jdnMCEs0Pu7ICJ4GudDen9rWMCSk93mkyqnYr6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T17:01:37Z"
    mac: ENC[AES256_GCM,data:SfK10KZqpcRqLIJW45XPkr+3Ue7uCkl1oEOVxd6vpHft4KkGBIpDgVEfYDWl4fYdyykZNkRQZcXoEYLt47bb/EddhFBQixHO1SO1Vpq7+uknvKOf6yYUEjJYx0SSWo5G/MSo+hcBlvuhbKVjFsomr2gm5sxZlrhJrlAoG/d8Opg=,iv:7kG5Ax95eyW8JioAlFsoI3GhpGYaJQ6lz9s2YJxNZUg=,tag:24nk5Gu243hYhIpemMaOnw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
