apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7sWYm5V8lcxdGRNKeB5u9cnIJ3yMtu/D9DaZqGsIlthnXyJUQu0KkY4S+6M4m2j2caYF4iE7o+7pSezo/WxA6TfPNnEJvhZPYB6Ny9dASRWatnW+RSvF+lOWlgweicbTHlZFskdP+IjbVdhPM7CP4O65zu8z1LN+zBPnI9pEE0DnkO6N0dJgcFZM03LVryz2StTqUXktpLJE0uweHQRQZmj7LhcjJSia7Du1zeURGwKn7noMOCnWavYnrAB1loawKwO3Ok1QSUWapWKqIYLA+BkArCkvuLOSmxE5NJUhIjKet+y1n0v0kqOXsak4qnThtAK1XmC2Rky9vOCMexBAnrD8QRI6OhtfS7oE08bhdB5iM5GgejNj7yukgveRDpQ3,iv:CNNzYSqLyB24QOp2BN+5MRdEMtFl/3TGliWmvjqWEcY=,tag:wLt1dK1xZOtUrT1pyWA7Vw==,type:str]
    identity.pub: ENC[AES256_GCM,data:aawXFsu0+OVeZ3LZqCVhJ3NLnzFOT5/lRrvVJo6LoJnNuoQAPIBUlhlCvQXB8uDkEp0irtF4vCQxPKRytZUD8eHN1l3/Wik4xLWt75ppboLPJfWKd1Bvg8YQp4UHHzm4f0sPpxnXROzUYZRWfcyknQsOUSOHUGr3AtXKFnQVkY8KjAVK1/b3nvUn/v/qdXoClq+mzDERriuCv9mfR3OBSN0aSttrWo76iS1GptKjDyg+QXtJ7+Rz+EaA/wC/flA29+Kz1zcFCYzeNZxHtw==,iv:yNsx8zbra1TktAmWz+NI5Gm3fVGaNqGVMetafI+m5Eg=,tag:HcXaNH8ZSYAZd0EOe+WM2A==,type:str]
    known_hosts: ENC[AES256_GCM,data:7zARp9HnYcTixatM8PXUC+3lFn9/jif702WoquTMZa7R35WeWnt6qJtu0FWABC0ZPH9k/syIDHCvkBSIl0K89DHE3mCdzbQSp4bJOpJssOhTfPSUwcKW0+OYUlUwGBGJ5pXPmFsqTCxvphXjfi/EXLJrGvUbnG+TQcSK243m9rraFbw8mU8rK/YNh0F3bWCVwAMau3zTfDM8I4FZuIoWp0uO/mj0kzdxfCUO,iv:ruU8gQF/1TkVkSldRHv9UY9MqhkwZe3NmXHofRpr6Pg=,tag:bZhqr22Npa8lBNAng2B/FQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEL3g5NnIyYnRHaHVnSXZD
            VlhEcnA2YldVbVNDcGs0TTVWVmMwTVdob1ZVCjZ6ZndEWGFJK2pwUjFSaGNhNWxL
            RCtZcnB2Q1Vlbnd3eVR2dnhia0JKdnMKLS0tIFhMNnBBTCt3aXN0Nmh1UjRBeVFM
            U0dhZUYwNHhPYktYdUxFT0RsV1ptdmMKNaAD12L0viuqN1Ic/G8Vpd3FzIDt0R/Y
            0GQyDv8kLJsQpZYHeOF6jOf0FVw9oqv67EQSH3sQYdl568oHqY5JdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T20:40:31Z"
    mac: ENC[AES256_GCM,data:KacsKNx/tum89OiSAkqBvmy6nfNaj842YAUAQ1iFoMKUd8+A8Ar9Qgfk1Mu2VqvuDhxJ2vFCpm/PdzP08p8L/eA1BmvOQBC5HwIPXB+GZaath60qjI6sY7Mjq767uCMvOF6HzTg2h3/sdtUvcxpin3QOjXF2Mdt8nhOCsijjwI0=,iv:9NeDql1hGNJWf0ISQuDqkRQgNkMQgWXQDS/wt0ZSsCc=,tag:3WTszo7KqpGYZzbNxNuZTg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
