apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dldN/zgI/ViEXid8kNhuRW6+CluvsCp/yH6mU34biEFOEtU9W9eE949p9F131ALOoT62/meSTSV/ab2C0noRT8HdBFLyo1x8FrCwflsskRc1SQLouoKB7oKRPHTtZnnWZeo0wdXeoCEqgkkqyw6P5dnPUBqZKWXbXI7Wfmh75JUXyF0kGWDeIokBhYBjSVzL64Solzpf2+iydUpANyTiU+Wf1bJ/DZHjXV1z8y8h43Qpsa93MWtaeFRI8cXjuJz4ebSGGJQ6QARFPECZSaq3zIi4Rt3ASwownyxe2Nu18eL1eFWkGZgPIFPvnGTRU7X9rhPN2z0Jg5Qv+Ns20C7u3xBIsLKjDqSTyEA+eIJlTOqfEGewkXKch7W6uQkboFrY,iv:kfz+Np77GJpoFSoKTiG1e3ysXpTMMYqeXcwZwCL2LX8=,tag:fGGqpKdQeUcTDmYdfjN0tg==,type:str]
    identity.pub: ENC[AES256_GCM,data:IwxMkSXTGUvK0uNtTn/5iExvkU3ytIhVO/WWSHONRUIdlZmcLKPSOCZCOK6Cxc7+ITZgNUpqFyyAUlKe9VyBgvCrOM9gdkyhRsicVFqSYqN59zl+jEMok2h7jAcI1GaEIhmlwFf+QRTd+0ppbJh6RSh2gBDBGBbgEGJErimyOj7p3PkiIrl0SxAQE4dvcqRjyKjX1lsNfZcCpk3Vx6a/dMx1rC7mYJgfx98LToizqnSJ+7pbcMx6jmrygVKb8sn2eVVvchtB29w1oqPxgQ==,iv:Z1ZMVi4pg212f+D3TbtL27KzGDtZhCxApJ94m7QqTp0=,tag:ESigfCEnKkC6tBOzXym7qQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:bhZdrbZJvIk/uvXj1OFJsUM+/Vulo9deHOdJKEuRZ6sqOOo/IUpzPSmBcNlcqQgYC8PBiaj/eRFYpP8SVtTawT2MtenLVpne5rCvXAb6tnuc06p8TjGoCXOIcN4kTXtyDklizsaOCcw3GOtMZYeh7GtMjujbf3Yz1yol6yYYFl7KoqhPxmoIlb+xbxWub/APlnkmJLjwXZe0f6SaUpZdIIpofEEOWtO7dP1K,iv:holvKCJaJayzlQToCliSbUEh2fdI7EE1z0DJMI0n43Q=,tag:g+3sREhLafwz8bRDcY2jSA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVmlOMWZ3QlNRM0gvVnRw
            Mmx2WldLcnpsRXk3NDMrdThGVy9KbkJzMUhRClduVkI5U005VGVLd1FNTEdRZGdu
            NEpnLzRwblVkQUxXa0wxUTBuR3d6YWMKLS0tIHZ0T1hsVjh5empoNVk0Nk03aFVE
            ZXd3dkJENDY5SXB4aDg0OG9namgwMUEKsAk/L84LG4CUjFFO2DzfB0grzWjLwcA7
            wRGDUeLJgV12OgEAnGeSCc4Y1SG7yzWtLTs+rqdmu4hXzayQfGahBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T17:32:36Z"
    mac: ENC[AES256_GCM,data:lSolphYBXtHy2RRr7TSTw/5iCN3CiHwW55QyJ/swWpE6+oNJqWQzprAmOuwUtu1wW8UVOg0dh4yzSqbI/FyDkDSk0JtHnNlU2Iv60Daj09UjIwGGIb+r6rVbht19HT3peddg00BKSNyDNOPYgSJbvIGpu2WujS40hSvOJ2G+hIQ=,iv:8x9ZsXPn6aR2pLuFjlFkVPgIDM5h3qeYLiW0bbUZjfI=,tag:324Q5JIt/zSP7XNkyWVnYQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
