apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8qpjJY/YSsK3z6Ioa5WFIeUroQZ5bCsvcKQgsb21sThry9KO9wLpuqt+GL/zFD2+xsJ8hVfA0dWUuf4C/dYebJEITVktTZN9VpJLtcUzUFQvvNZMazgTwO0AyRt5nAhIlHVbl+Zdb2zkFzP3ZvRKgdAoHL84FTj62W50/ciPIHcjUovSEfeBRezQJdioMJZsGKhuEEyGSUGNaIxJAiLjC8W5aNgJlLD/gTDVZcrqBITrfbkz6hWG+B2ptNLhhh7uefmm+xvO3FuT7KTcuop0a+w9ptKnYrlcIz9xoeSiSWke6SZNim7J9M75E0NqIDX2e5NY3kZAMzWjLM8WoHbScr3qpTiF5TugtYcMK3OJRFGL7I4CzoGBT7OHIIuaVYEx,iv:aDlJqfJRYjUNswW5xuqCNjATxqGM5IvpQP2Knebt/sk=,tag:Ujlmk5xnYcv2HlCeqzLbHA==,type:str]
    identity.pub: ENC[AES256_GCM,data:xAVB/Oh/0zmkOK/8cVk/ZeOvr+8+QjucHgGLEyilWahRe2nmEySNBmIrFwlr0cWulJGDsbbUhIdXAZ4dldcDHRgOWIL1RI7fu8UmPE0k698O+YEGzlrFfD056TbgabmZHntjADcbhZymE4zbUticVaGE1wmVU0QLxqlF2+2UZy2jRZCON80hxBKywCGLu3y1E+GSkdymJkmugTR3cWO6cm6h30X7/IxF8UlxqZZSUisaMT/Of/fJItCpiJStN5NiaeUGc8G73gRXlWqPeg==,iv:nymEVUDJWJPW9fz2rMItDgWzBtRj3mdnMkTWi5e/gF4=,tag:rw1CIwvaJW10v+NGxCYXiw==,type:str]
    known_hosts: ENC[AES256_GCM,data:8YRRYYG4ASu2oPa/J6WuQEpc/j5YLZ10yqhXEpuHpBB9p6M1o1uCtQSnUPyxT/yEIqz+9shEOC8tJgBlgJgyIYvAw6z2h8BQ6UEhYLAdQ3RWunuOtaubZ/2NIcw+n5Czju9xefZ2kB5n/4CoQbJD/bWzLyJVWUbjofjwA+XTGjkbbkSAHNsCrnjxI4iBHoOHLr8MR1dc61Rum1uTMvDZYHpTclnLEREKPzqZ,iv:DNAVouz4h1pkttrSUCVM4YlN46Ck88WaUIltlHqs/DY=,tag:PsiUHkaEtHu4+gwhVWWSqg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRm02OEpSMHdXU1FJMkhJ
            K3BNMEJBS2RGMndtc0NCSnVkeW9LTThuaUNrCnp4UGdoU1dPQjhXb0FEZWtIZ3pz
            OGl3MGsyTC9TOFlSQmFxNGh2MGpyRWsKLS0tIG9TNkVVdFczQWFtZTlRRVdON0Nz
            b29aMndMRE15K0pKMzMzbVNNbzRONVEKdV0aP+6/j/hWgbDdN7hUUEEf/eaSAVa6
            MywkiMlJ/LfjL6YHcqBjD1CFgHwfDDfBCJD1KJbZf6TRy1iZrfoaCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T12:10:33Z"
    mac: ENC[AES256_GCM,data:Jl7bO2GUDYF9o2NtyUrATWhqbIfo4NaOcmw4o/bpqWGDR4XnjZ0SzCoL2mIATzzdwGFZMsTs5d3EU3ftdmZo2BQl0ttuEt+WvRhM7xJv+qNewzeZw4JXf2ilMBzRbM6gtGEGdrznDDm4AuMIg6/UNqtIIMbgyZmft4/DZIQ4nUI=,iv:2QSfCCLR/J/qA4iv0Xdqc0XP+ZPAz8nv6EZuMmLnvMo=,tag:D1kc8vUVHYbAPXngXOO/sA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
