apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/5My8WHUKe0fXb7t+TqBYHgVPAAU7H3zoOFiozB686GN3d1HvJgojD/WBWakaxTF1pbdhk7upiuvpEFEWKkampulaJ8mir35ZqOHOdTitlzNFuto1BwmDE1xigEfyChBBZlpi0Uhbb8CrspADY9Ray81ijebd5hYnzddgSo3Tmr8uh3xYPPymJO/FZ49ZhwR6VEDEmvcGpmxxqaAs+g6MtZvdJl4mMIyG2WpDg82sOnD7YkP4COb66VgsHPFtL1GrS6gwxTq4NHeOBODe9TgO4FEC+UPM0kOW6vUCNbkvLkFWujIKBa+9t8yXBJZY44EZsAvpiea3o+2CgFQ3kGrAO7Qfasp15BQcTLTHc20Z6NM6hQtHFz1uCI1piWRLD6O,iv:lPe/kjz7xNuh/YD+LjiCe+eHm3j/iDWNEqknjzTzWuk=,tag:vcmTjBlKztahaXmuMPbTLw==,type:str]
    identity.pub: ENC[AES256_GCM,data:WBlSTxOzoSrEY/D/d1ISALx4gxKj5IcE/nPoEcgFzmh0FyqsPDDhH6bEfYIj2vNO8fhU3+7QuXClSIwsbc7yubo2rU+9/EsN4sfDKxFKLXC7Zx9c8bOlgO1gWGUNdBGBpiZL50niOyG8/wf6FazgV1VAu3WSKV5Q3Byjddp3DZ3qthkbLsPSB/kiRdyasLgl4pa4TyBkoJfaoDepuUrTKNuMaDASihXKyu6r71kuPwIhFIZttfVja1tjEoVgrDYxvaqU9wx129/eakZagQ==,iv:8d3yTDXQhyq4Iu99pOix2htVHZukZLj+8toPLoWfB4Q=,tag:iJlKJEH0EHfUErUxMrJ1Nw==,type:str]
    known_hosts: ENC[AES256_GCM,data:IwI/zZ8ggVKSqZ59fw3djfkh7UtqQJMd/fXUETPvEfDZg9AyXteNV9MFLZMsc86cC2izhUul4TwfyNJPcYxVD2RJdxSa+Y5kR9CMPn9ls+n2RFPIrtoQGJHFCbFbWc5USeSOohTqxxjOEdtJsXWfa6p1TA7Y6vHcr8A3vxiDNZrHgwoS/dWFRUP9cVpj4BRh71mY9HdM+JX75cRBrX88jSld7gBu+3KyAzBi,iv:XBnXAKdZCpPPdVPnw5wSXVobq6FVhlRgbawuW0WS8Ak=,tag:gckO0Db4pHhcOjPZ9+JTjQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVmpGVzZGWEl3TU0vL24w
            NnltOFI3RkpWTE5XUDFqUWd0VUtlVTJ4eldrCnhTZEZaS0FTd2YwQXgrOXpOdTgv
            YlRyR3VQL2M3c1J0ckE0WEJHYkdVUE0KLS0tIC9mdmJ4L2tXNjc4RXQ1TnFMZEpL
            M1IrVWk3c093YlRhcU5TY0oxSWdnSXMKch298Jl/zUMkKqcpn/rtdGKlkPagxKW3
            oqEIIwK4JfPghg5F5GnSQeAbvwuRrmHMIHGCoE4OVqQjuaFeHJpX3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T16:01:11Z"
    mac: ENC[AES256_GCM,data:NJudNMyUoH4Bcaw4xy08woxY5IJZeTKAuOjmlj30H/gNLj88MxhuP5LD2k+CX0tIY+7RWC5DEVkGLXCvabc/DfbjiyW87is/FDro1yWti+6O7tAxpYi9vAVp8hgIVnJFKvpzjF+IRSFMSNHbfuxrvt37H4tUPwxtzOuYvdUiQvo=,iv:kT5fUMDJp3nk6SC2cJErsBljaZpGW7ntYktUl4DCWsA=,tag:ZHmfyziwu4mf0NgRetFzxg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
