apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:x7GwQ8ATCoIYbTVJ2XxOfZPuceQj37MH68PPbYeIb1s3aLCSJuBFvZV2yYYh0aExuSXdOHqzqIUsc+dPfZjCdA/jZZglLdJ5ikr/5B5nNLxAq+uWv4e6bvEZFoGyn9DIOUPgYkxUa+rQBGj+ZThWVmyBfkGlbkjALp+7Xm0W+KteTngPcDNxNmQBqLM8nlv9ExS1ubGNmRtP7amIN/daGpufvsSmKvZ6hOlb5yAAqS7X9a0A95A+7SG/ZRKk3cRoXQiBWp0fk+9Jk6+n6wegn/c+179hTKfd/OOrijGxnNaQvfC1rzIFg3+UU5OvdiCfrgFPlUlNxLDyKBeY7/Mtx+XUDCfze14TLnCe2bXhz9Nwxb031WAYz79Rn4SSG4tu,iv:hAburO+WiQUVPwyY3fDc/jVPDVVGM1+p6Xf/EgoIOAE=,tag:cBlfgwfC/RXkBaiBJH8dNg==,type:str]
    identity.pub: ENC[AES256_GCM,data:5sOPw4DCFM6seH5Ks/is4k+MqrA5i4cC40xEt7diqwwe2A7pxWDZWAA0Q1c3oqxgPzLi+MD31b9igo0FqVnssmVC8ubRm/dXb9cOMGPLfq8MfdUvWTQ9psAuuzKGwQdbGafPpzYN9g3XCzRWcMzS+Il0Zq6ey6zhti5gxfJNeRRsXq4AYtez0gDoS1akBBccjE4KSqObJygv5wc4OzxZZrZrC9IZWF1ay8Md09hQRX1XUxn1COw/9T05TICPYZmqH+go9yn2R7bwForOOg==,iv:MMiEY4HZheho67AniwS14C7LRc6kAc78JDk35MtwanQ=,tag:VLbDyiBC0Frm+vKj7PvRaQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:OKPzYIO8BcFAYrI03ZYXk2iP9Jlv2llR7+dkRnbZsqtQn2M61dXQS2AiJVLEISvQ0dlS23Np0t2lezszRw0z5PfU4gh1EzMbQPYxcifcU4IhL8DsTGeBOBKrhp4vlB9PolOHc1WqsAJWu/vYYJaKusnDVIJzGdpqPyBgiB3eDffCPoa5qS7Rr/4DFfoAlRVCm6dlQ+Mw2EHWb6mhdv8P0WWnJ2Eh2rxhdl4z,iv:QFf3mcePtc38u/LIULx5kg4sDtJ4N5C8vkkNV88/Ths=,tag:/lDc/lehjH4pV5dlIckbzw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YnJXYm1wWEQzZ3RudjJ6
            VXV5aWt2OFVLUTFpK3NucXlSZDdFT3dRQ3pZClg1Q1F0VnBIVUp4SUxGbVp6Yk54
            TlBabTVlcFgrRTd5a08rWUpKRzlFVlkKLS0tIHU0SG9EMHk5UTFRRVJrMUJHbkls
            dnRqLzhTQUluSGZYSGZNb2JWY1d6dDAKmWQc3d3J9i9Ybe29TUctGYxkoMQwQBuI
            ZvbVFQ1omYhnVgrYLdFECdPd4p3kUXRd5g7lMwoDT1E8Pmm0UesRvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T17:58:12Z"
    mac: ENC[AES256_GCM,data:k90ISyZneD7Zutx8emilAHdhzc2HVRd3FETxV4ylMMxhKz0qLUsWQvnNnfvwe5d451Qq0sIq0U0xfS8hjT3bL+O1LyGoVpzZtFQNkOl3Ffx7xt3Sx9tuiNUeecT+NXf9KYj0UQDxlamK0dmlJPxgkh1Er42cCeLRSKvNHaq0wEg=,iv:AFO4/1WdSHrdpcV1nXlS+z1YXLIQy25pbePoJHp157E=,tag:SgLFaxoGcsCsWAXYJDC9BA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
