apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9SZyibNRT2XUv5FAJvMj0RJk1zcpFc9XPQyD+q6usDYX4KOcVBsL9DOkuDhslgYZ41AlZFH51Ok2BzWdu37gWIcd2c+ebDgwMczEan/5X2/fdG6hqo725ZCFiFkeg/LfR6FfPrsbuF1UG2hZ4KdLbnZcQ0lBW5xg4a5zX8Wd8oZXumu45UwwbegrW1N3vrY+EvhzNOUIto6x34coCTgXSMcjtMEBJtXTV4GUdj+HiU8PJRgWUUoESxifuaj3vGKB9iKeOWAxLyBleJtmc409EFboS2VQUYwYlE+47wYdC8iItMySX6q1BsjqopWPJqGwJanhGRUDHkzvLfmaVFz48BzvmpbW31JKbp21N67ubnpctzGwhGdhLstc3RKgttpR,iv:q7P/uEF3wvCv5tdxCNFqmgHTlDZzVcOmyRlh3Yz6qTk=,tag:WxWIgGWI4MoY5W3Qn2aJMg==,type:str]
    identity.pub: ENC[AES256_GCM,data:p4RxGTEFlN5uu8FaWBdgDOFtgx5jVp7X0pPLoxFDiSG4u4NPgTZnZz7lz+xyB9j20XjtwX+ICmQnQfXQpBKJa7wXqT/sW+B4GWIJSmyemaMn382PIFnd2eQRizyhjzpQSWvhFhtYmkDw5EzIBbgh4JSoXWaLliVYVQC9pOYNp3H5boqfxVLKk3y31LoP6VXB0Mp5VEttUNkgOln4IHsPKh6gn6H4PS23lDWNfilmwyBqhND6GQ3pjnGsmF86T91pjAyhDXweS1xbM7V76Q==,iv:qiFca8QAJCm+Val6C6IR2Z5RbQLk5IxUMwqYn8ynmlc=,tag:QLwPIBVkT6YVNCEhiTpLNQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Ay1FUxer96XuG31fsc71+SyCffZHypO5L3zTUch82Fp4J91ll+MHtLoNthDWnyA+w9uuiOiOWg5Htyxwl7FcdpRLxZ4xFyUekvEYRZBVAdknhnT/3J32jnlzDl5oDwtT9bYbdZGRduEI1hto52r+On45Cct3zpvTMDc7Qg9oEAd0QkEZzge8Af4DuibK+ci3gR9GK57rxHYMDn9/kEvVKdw0HYB4CRs0TGF5,iv:NHjW0Vy7GintRoFArl60Bkf7RHX+qZk6uc7vt7jGQ/E=,tag:eQuV9LUQkku7RgXTxFE8kg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaUNsNTRZQmRINHdXWUdN
            aEFIUDBxWkFtSy84dVZtanA2bDJKdnBWR1FrCnVBNUZkL0daa201UzNkQ1huejg4
            RUtPckxpeExIdDVBbm1FSG82MlNYeUEKLS0tIEdZTXRHUmdmRE5VYUNYZ09MYmx6
            NmlQdXdzTnZQcFN3bjZNb1plajY0U0kKmDSWi+icjRZgEtdGPpSzJgFtqATVXZrR
            z6ctNlUv0uLp2+qcLNlMrbk6I0eaXkGJ3nqWUBy3OUPv1YpTHMnjsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T20:21:36Z"
    mac: ENC[AES256_GCM,data:YJHnOeX19YBZioHy+5sxZhD/zKz1mTErdkvL6sfWaMXoxjWO5+K6Cr9Rn1lUTKE9O1j9BMY4x9+KwgpBsDnyuNu72bBdnPt2fulYDw/5pIb83WScGsdFh3usKadxueTQO7NwUCMT1ddTutyIfsOJEjXx6ECNsZ4oKTDJBDDmGDo=,iv:WCQCjE84axHHPyFQmyJNo/ewos1UjjBIpMBtBtCOPts=,tag:eXRZFlOHbWPt2u7vaq9Twg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
