apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:86YOUbt2xYC8ZNt4aXjrxnH4YHOZRxl7j2bdwQa7q4z+MljRha4jaraWO4I3Ij0YLDk1RA20F6lUVGLW+PBhSCkwduSfgkCnRtee1rkWtHZ0elMoL4VhoHOHm477hIH8sjFnDKkIT/N92QYv/787hqPIhO79e9At8TgHH52WG3kowyBvYkLmwU7oR6uYcb9744WM+hJYk2hjSEd2KoV/TLuhSZKVYJ4mo7xXlVT4+VfotIptJuIB5kqrQhhjOYHvkIqLYNH0e/8gBR6rDaknWYWVFePOUoJvR5vsGr8V2BMN/PN9kzvzhXajS7K0ZkdEuWQbzsunewouh6jJPqdha0nRGIY4LdQqsu/xtRKgjOJSQ9laQuMWZ3ZzjvRtsSi4,iv:AviqnSvtihev/+92J9316p3adwmE0dF7f3IqZGFVtPQ=,tag:2+q+GJ62twevYEvohwNGNg==,type:str]
    identity.pub: ENC[AES256_GCM,data:vd/SQsIpd1n4h0aUmB3RwOtuvC7OkzI01MEnHl5AUSq01egpsbx7kB/CKOzCLthQ8GMu7ABxueKEgjYJsdj4lDgO0XlChu+0HrmdBByebL11siK4eRWPqo05yhFXLAllLQcz28aBs3OTHIPDIFn7ArUG8SBE4Nk/Ix9O0t3TJLweKY5Dptt2EFVJESKgRnP29N0s+QOTcjtm9aiN4JWyJSxyf4DbaxRrp0Q4GLUx2xXjPV1XbgT/S1RZ8eoMgxrwyoY3EEWTMA3+HgV+mQ==,iv:fO9ATyfMgoCCElnmILBnrthK0lra0oVm56NKyzteC/k=,tag:7PZcB2luhhxi966AMncOFw==,type:str]
    known_hosts: ENC[AES256_GCM,data:GuShLKwkz1XOY3kX4ixUihJR99MtiPYgxVQTTgI0fqM3SYJ7SA/OdyfosOsc/+GYSKPT8iqKfOTnps3oL8qUC8olpxLeZwCu7fc/A3piCbQSVrA6fnBQrf/Wu4QzyG4g3GNdJgar+3aPt+evjTR6QhiedkZiQQyh+0DjjDuW2RfyCeZenthwptz5358/OIcQ661y+lzo8nxTP4Y+mM7AGlXwB5T9TQg5Oa3p,iv:RJEEt9kdofWG1rLCp4h8oGaxkh4oXlwaBqQP0DyT3p0=,tag:2t+SryIhbtnav92Q8/22OQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUStDQUtpTGhOTzdRdHhY
            Q1JnM1FvaE83WlMvS2RxWFRPWUplMEJRRUNZCmk3Qld3YnlnQTBDUytpcEtmb0hE
            S05aOC82ZTc4cnZ0NlN6K3JUZHNiUHMKLS0tIGM1M2FVT3lPNGJkNm5FSVR3aXY4
            NXA1Zk1TMjExTUNXb0xBcFhDMi92aEUKNnPdBUm2idCOEacPVOluW7uJCsuOwrq/
            NW70yYj5OKz+huHGkS9Mg+qoRxX1Kpb7BzlR0zp/0XGvuAmMdURqEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T12:49:40Z"
    mac: ENC[AES256_GCM,data:he03YjrUv9rbKJJlf8fnt6Hf6zBPYk0HfOVdB5XsiCe9HU3PMlLan6xUbj9lhhNOM+uz9zaiaH+b/i+cQHzg+TPgcT8+M6ngo+w27KHSaV31QWJAWe6/OSPpj410+C8ICzEGtLc7xMdEwTW7IQubpZDrMgptExIUs49v/Uk2ROk=,iv:QPWhBhjcc0k6kgwW3npahsDkXv+OJ5y9f4IA4GibcZ0=,tag:0oTuOpHqCO9Q0JfjYmqOnA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
