apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TwHBw3wst6QTFXDHZIhNYjT1bXyj8xoApbKe1CtgBy/k3Hl9gBCRhw4JmIdVCcE/9LDa7IQ2SJba97O1oe3G8GWsP6oxIHFMFtyw7ULMw6GUDtpxxMPHR8e1KLcujEiB7wp7vP6JXyf8BsiV3TqfdgKgRDjnKv5hMggOwz2btI70vQ9hrtYhyrsExw2zx8QxdG3wovLeYNJUU8Ze+rHG/rf+sr4Xw+QdNu7BMQaBEzwKTFv1TF021Q+jYvZ6MC2uUR1txAdjC/zyQTfzzAFh5rRRE0QjxYIbbfHTD/uwYOdKJjNePOBHqPfnb9/zMLSkSjFn0Wh6+6z5UjpfS7ntcmbxd17DmtMk/RJQWM8zRLARI+n/gH5iuTskQlS9R5ql,iv:7REAdd7kWzzBUHFJpNijnfiZjzV6OY6bzdnApwk/u8Q=,tag:cdhHNMf2SiY3eXIUwxVOMA==,type:str]
    identity.pub: ENC[AES256_GCM,data:J9A/Y2J1GhOhseP8bKBqkn4XCcvQ1vcovLuxPFeczeemdj1AKq1R5HhFPV4C+9vRevxM5VzBEs6OmTLAthQrWVwJ98HlFFxFqckYsXcl8eabcj6mWKpMDwoEzHrDAuyVRmHN8mrpDqSCToM9+ddZ+0i//VZhZm22DxZQsjreTmO+lal4XGXalsQdoq+jFzuEaa+unwGlCOckxAsi0WOkv9mVFI15BqRXP0Lw70999fGuXis9ARdsrRNgaXOt98xs0+qacgcyVucVpOv+0g==,iv:AG4Wxraf0JN8ynpAMYo8Cd1b5jRbHG8FBEH9y2TsFYo=,tag:Frarh96U9GwU77lO7IUnqA==,type:str]
    known_hosts: ENC[AES256_GCM,data:yUNhIx4B42LImQgUCF7fVkC03HwKIj/T7SY4Rc/Kvcn4yZJUPdkLr8zoD/ScYuXT2B4/CSWHOM56x/oh64i04z1054NZXufqz9Ntewu6dZLCE+MsXq0FLjb1pmGYWFB3z4sFxbxr25V8sh3jZIJH/YhyucFxbVtPTrlIRIYLVCZI7zI9PpHwEpkTPhhCF1xF9lOf6GuA+bwZlfxH6tlVILJabT/X+e8T2Yrj,iv:oo4cotpZNGgyj/YBYgnSIZoYiP2DbaBeRYQqd0uP8x0=,tag:KLQuY09gKvYr0iXcsYlgEA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3K0RBQXBFOWVRbnZVMTBj
            Y1huYWNzUmhqYTlXanN6SXI0QVZrQnNVTVY0CitXbVlsZDRlQkJrajJOak40cHda
            YjRUZ05FM3A2dkxCVjhKL2ZTajNjQzAKLS0tIGZlNWNGTWUzZFBOOXFXcUkyY05s
            NDdhaGtUVXJPS2tGcG8ydEpqUkZkYVUKTUKq4q01hFzuYEnltoLnoIIeFdenNuXC
            XWOo5UjDzGx1/o6Abh/ir6omwsQDln+kzJ7ZtSy5IoZ/jaG5ejgP9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T21:24:37Z"
    mac: ENC[AES256_GCM,data:4MkrPNl9qFofeWr0Oq8YatILQgNsBdqSa14/5h/qn8ESlc9t5sTfgNsD2BKZtP2KXT6fkudBHAlM+USMAKt8UHOhxvMCHzPOmR1/N0K3DfD8JcuJYf5eP5NkqFq91G+h23ct7F0wdEHQL2oKib0GwsQunYHogaeJ3KgDTu7FzWI=,iv:nfUbMJwSGalkspK5CLOR5avyuJQp7YGxwMtoTq0XrJQ=,tag:ultQNwbzEmjKMQ1BvRZzrQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
