apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:X7iRWxisuMCJaxuWcBLxx9yCepVJBymxT5m8GfZnVk4HaexhRC7QW/5BKjp4VFAeaCdd5pLgnlk2q1LqDT7M8eGEky6ZqNtljqlOxJiV8XZmPaJL8tZWITNc83yL+RCpS4+uSu53f/NGoS4BLRm6aBIDF2UDK2iaQ3wEmQKOqHEzOmEgg5NTblujgj04vGJqv4QMud6DSOPWjEtNca3lGhyX9JuCr1eDZlVJteFqYFmONmPnmm0FK+Y6CZSNgS5/zZgrZxVDB3INMzZD4E2oKSaAMPOr1EEU7xGspf/CtyediWN2uJvBDBFjnVy/8tbykTD6koSo9FUQopKvhrgSB09AdDUB2HwKPXJEXrl1Ro0jCW5eTe1YmkiP+VKJjIHM,iv:WEKOSELhHqayRVIFQHzHjCWLcDeBPvxxTuDG05tukNU=,tag:nOt71w8lzR9sDVOnavB9Sw==,type:str]
    identity.pub: ENC[AES256_GCM,data:w7aO1oL6zP6YZVuxr0NRx+EAFuG0nxCtxAo0NsDdK+xyOY6sXf6WYxWpyqpM4Fdo9ownKk7FDvfi5TQ6+MvBGHxXtw2ab8Q1fE0qAqwRVIOD1mOmSrUEVhy8Fni8Tv7RVi1wd+oetGBAkYx2R1oKx3lv5K+LtbkCiWXfa3tbbfBGaZpvepZhmtxN/EgyHGlBt8ZojgLqNHCnJXa19SfNqn8mj4ymxIGMrOT92cxzYRTEGdn/NjDDfxuMwhA9LzR16dEPcIfABVye1i2Tng==,iv:og2T2QQm3SOR5mFJVxBGZmPHbxp2bodHzsLOYPulj4g=,tag:cJ9WjXMc5imV5K6Yuz13yQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:gU7++ZUrDXy92EF/oZWDXn1n4DCgtVQXFYUqiFFviRAjgJV7ustnyFCIEwiatNZQSTwy6fTaNBp42XCWI+S2lBWiWvXAC0KGQoQgKnL3ath7ghqE/LBqxjgbOx/tCIYwC4E2yU+NFpuayFQVNLG1bymtkVvl3IdgK/oZHP+F5JMfkm+Q1oVz0ZSAJ4AkB3ZP6qd/XVrUA3J5nWewkfrWxPuiKjAJ+7ww47PY,iv:Wam4v8eYp9lJX11UcxmVV12bUkpPk/tepG2Rl6ltZNk=,tag:HM6Rm49MQhfXctJQdeQUHA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaEVuR1BiQkpqOCsxK1Jp
            RmpPN2FUSDNOaHpyWW1YRVd4Q25YVW5MRURVCjhEb0NYOStVR1d4eHJWejk1aE1s
            MldkSUlPaTFBV2dCTkx6K1o4Z1RueE0KLS0tIHdITHJuSkRGOHBCNlRiM1czeTRQ
            MWE4Z1piNk5BRWprTTVsaGEzMHN3Y3cKAxtIYfIWHnheU9Zw70a9wClyszYAMo7J
            PZ2ybDcCwN1etlDH2EVjGhu87Fq6O03TmhbadVdlXrW90sV7lTcCmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T21:12:27Z"
    mac: ENC[AES256_GCM,data:KInQAa6gZxxS+UV1U+bNj2c9XJqqcNCtlavoBJUo+Bkg1HOkNNZk0zt33Add+/QPtOh1cqq4xx+fzqVsmNHNOgnE6FuxsRv35fkxuy2zBS0mcE+KwjywTZXVmMWY9jLJd4HqmV2hjvjz/Lq0dx8lr1DEu39rs2JlyOTpU1hzcZM=,iv:PyIoPyGBFdbQz+45k+x2YuRyeZpqXAvyiVv/8ilabZw=,tag:lN1bb46fcltyZd4SboWuNA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
