apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:GDNDX5hN7YidUx2vozjNvk7S30VoFj6rxmiiUB+oYDcYHYRMreQ0pZ3PxWGLKJc24ytbs/T27R88XYas+ngxQ+FB3DFmKYOMIBPvrV8bOW1cpxTQUIpbJ3eCQ5cbtca0dqVx8BzwCVet6jCCDGXciWJ/3O7BLmTaTXoSHmf+vUN0Xgx+X3JW6g0dS5EB9CT4vFeG+7JaDb6ZxK55CDYPVAJO6la9sgh1v6jksI/r05NWmR0FniZYya0Kowx4ohGA9knHAWUJKDdT4eIg7fZ6KP7gIjCEwWOiUiaw8tInu2eIB+1zP1dsRoKfplgfcgZps9a/0f9l73Us3tH2Tpeh0wFCA9StCxFbWTb7R6WKbnkcgmtI4jWR5ohsZyXSJvFc,iv:hosoAP87jfydHOSbWzKgFPg56WrZX8owU3Q3qZq8FeY=,tag:4d8JX3usY31zIHdAigcyow==,type:str]
    identity.pub: ENC[AES256_GCM,data:FyLRwlEB325Vvj/uQYKs25FqW/jEYSRLWkY8OM8zvTDThnEx5XptOHPoRe1oTvKG6e/EIUq08TFPpi/bj6hfsrouIL7ERj/yOfPL5cZR/5c2XBfocUtBKq11k7AYwV354fAUSOyp4/A4SBpaNiHU+QdvH8Yidr5JGHfPMPKRsE8ydyvWfRuiGdcONs7eCE3AISm0jF+214rhjWJSvZVsbBvEpajQ8IQ/gwbXhHqRzUWRR9U+G0E2BzA2Mj/0bQD/Hf57pLFY90tZFmhx7Q==,iv:KVDIFXI2IPrfkauVmC620qjSLejAA2DsihxuwkpWZCk=,tag:I/FYy/9k9oO1lZSwSrnafA==,type:str]
    known_hosts: ENC[AES256_GCM,data:DbNs/K5iKnhxJWrtK4tq3jZ7L2SHBfJL1LDVlPwOopkhPnO0FfhJuWXeNio4ySHqxLfyk8tLKUO/rcBICpqGd09Dgo+kj8Htg8yTXzZcorUGcn0a7lAr4bo28fC7ipXf/8DwwScm1wehijtEnuija6Og2m7DtkRXkUrKN7QDRLjlJkGYFekdKhjQKWD+GBf/zOvxVd4mWLrjvFxK9grAtvC9aUkT2bqRm908,iv:nzjuKjnf7goi7E2Qf2H0cSQp+RpkqUSle8rWsSzpggs=,tag:Zyi+TT91mxHJ6dGqWXR3FA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcGVIMUM5dTFNUHJIYXVa
            NFhnL3VOSTk3WU01UXViV1hUYjVvRmd3QlZNCk0xeTQwSDllQndBcXBUekVkeVhL
            aEN5bk5iMXBKcnNSMUZYWHFEeUNIcTQKLS0tIDZLck1GVkRQc0UrZGlqZ0ZlaXE0
            MUJIcytEYkt4YWhqVnBBWDRUTUIxSTQKI6s3RWbMyJdUCMAvMa9plQlWi/pcbp8k
            SmprV0V9wUmVvcYoj/i8+Vmv5plcrHVnkX0lAIpkkbV1T98yJKAmlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T20:53:58Z"
    mac: ENC[AES256_GCM,data:kxLTELbp8jIUr4A7KwCT5GnMXwlxJ1xrnwejlSPjy3KQNBJH3NNn/0zyulpnG5KIIiO2DHvh2ZjFe86KLo7RXlERKzZEETinVpT31LKQB6sT85Flexq2A9XMplqOs6wFGHZ3AVBcENn6Yl+Ras5nz0TPRAoAyAiLTa6XRltRGZ4=,iv:kpqSSF2hSBa8Gxr0It/3slhbkqwoixH2jO7bguuABmI=,tag:6lWT6OJZmgh3LfW5QJPUuw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
