apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0DhNVGJLR5dT0ZpXaUmIUe7wVNA3RBy9i50KYyewfdAzEJgo8Mx6IxhaahRn0i9Z6B4Ozxp5zeQVfyBBcnTDCVHcda9kdyEz/n+zaYvutIvrhgnmHMqJxrRI3tGCyeenecI+D+K6kcT2jlP/eass1hPteGR2sTuwiwC93GGOylWNXW+ImqYXMhs82N9ekuuYeIAFNSP4raEdb/LS5CjIX7n/X/VeiaCAcXG2bX3QqsyH2OcYU7MJcU+nq8qH3dqbij77wHo19Lyiv955rWv/IObiHsy0vGWGGO99XoGCZNqJ15rog+8verRpZn1T/t+u1PEbuPVwvrzmbrAz5rSd9mQi+9yvTEEMqlEUOpb9InRHky1KmcDX26zii4qseVFo,iv:kaPvsDGfXOkSnYD+7ukM1HrCpGpIqMgXi0k7J+wW1po=,tag:6LBRJlRM5EopitWtFwPdxQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Q3X8RCMbYiqF4Qk03fmsJ8HOZxCsVQe6HyT8EcN2FItBkXWfecTYESkM2LznUAvxX52C0aWSg3p76lZ/Guwq9RV7i3dDFz/or45E0z0trDYajYnUVOPbti4pE08vAg9AZJ3Xixa3AaGIZ23qOMUBeDlujCAVhXMSp6DUkWZ20ckFKU5hdU7gSzG8lwpGt3AognyknEaTjUDXPzJXi7LDnpSaTJ9cNF7xdr6tMxxXM636wVOWHiCBjlHGbBWl5ZF08UX7dRs6q7uAiUm0zg==,iv:DI391eNS5GJm5rOs04UdrdAr2dnA2x0roEgVUcb/oWI=,tag:foyNw3S+W9dgS1Llt3tckg==,type:str]
    known_hosts: ENC[AES256_GCM,data:wMr0kfSZlgQtKXXIhYWv0C1Hkz+Jp+llPJA1vG3wJGSlNASL6wIqd8PfVT7q7eTBF/vTLd9TeLPJ8pHdN+X7xTa2DJyx7KKEZqL1PWsv8fWaDJAJ9P4wAsAAWJtX/213ICwnpDUUl3uKj+T7tHPYywaf1sf8Rx0CFys8sv0Vibc1qjNQ3D2yMn10tdNHO0ZTJADl65tc4Wr4GrBAJ8OjRdxj8GPZxZQsafJx,iv:Znr81DTFsyq/6wfoO69KTgOjSHvO2aKAA6DG4m1fBCM=,tag:pvWJd9kCS0vEcYoWE264Ag==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQ1Z1Y2Y2ZVUzYWh4Z3hW
            bE43UEI1WEx5dEs5UTRlSjJFNDdSalIzSUZjCkhiL1BVT0JEQjVJdDlCYjk2eTlt
            cGJURzN1Y2Rqejc5aEZOYytrVFVZZE0KLS0tIGJBNUVEWTIwbXR6RTh3bXMyaTRW
            MCt3ZStaRnpYQ2RJcDFBUnFscG1GUE0KXZlD+WBbD6vIgz+km+c1uYwG8Q7U9+eb
            VowqgWmnnRZWAMBWFKWJzmNbj/rNGiRuF241t5wbunxsY49XX+6sbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T16:17:39Z"
    mac: ENC[AES256_GCM,data:jqP9lIMe8aReMzI5WgZbcyKb/EyAiLtd9DX0iNhfDi7zHQ8ecic8pcLNTNqEDcWWzWPcWpT1Ry2m6LFiww24sh4m5TDqHUjJwrIE2VvFKL6MkEASMfvOQ/1Ljv0YkaCJ72bDT8sntUbo3cEuJG+llrckoCGgJHDYyTu47p4CTGc=,iv:92LgLgnkCPQVsMWoQYCV9j7OrUiVG2vBiAbC1nQn/00=,tag:GDR6QpOB7bs4pqxaroCp9Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
