apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MwCMZzV3+hFMfmJsYWdcQWBhjD2MMvYZZbYYRmk7BUmShy4gBRMdCGnvHG1Flj4sFtz9zaECMOhMsCGxsFLyRLsW72h3RgZPsum2xQC2GUWXlRqfc078cTySQeWfycSss336qnBBTKA1/4rcCNk/tlyDXY5pyeSosQdqSU6ZEZ7HU0aLrI+CkI2R/msZFAKXK+lGTId+JNjdWPS4HT3HsDSIBs3ZAgg7TA1BXkFv+Ay1B0sNizhtjdXYiaXNWHxONU3vyvBMM+CBwv41CBY7HgCQmarNRmQBLbQnhh6ztspCArTZJza0TahdwK2fsmWGMWZiTE3oToDrjGXV8ezW5ZEYApIS4c8WVdkL8gCsLSfYxGsh4hfFuSkjy7rFlg3v,iv:LSuPQFt5mwyOixnH6Lu02ASs6eyqFig2zkcFTpVj2aw=,tag:hA+/c45hty0nCXmg+VQlOQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:e+V+5aU3cPr6ozHWNNNjK6RvFY187DmKmsmanAf1qa5bAGBc6NuzB9vCoWteohmR7uTCiffISRIs9bu4vunuuTtKhVgtgWVLxy+5Z0gkO0EzeSOhOpD2tCJ7x+6zAy2E+j3hyJKDjusvBDrYfZzQw0J+E3BsOjM6HOvTKGpWs4NS7XrlDOLnhwGdjaEtyOt7c4AWOro33+IKLxG/FI/pWJqNtu8Wdl9eD5J1m8iTUuxEleJjpuivVZiuQt/yCnBi7MhK5dg9wckEcAmFZw==,iv:xzGO+xW07tHZE4T9T6+NpdhYEPXjf4fbwXy57RN0Caw=,tag:7zT4F+7Q3FrMOsGTi77scA==,type:str]
    known_hosts: ENC[AES256_GCM,data:1ZApc0oYMiACXB34/bOiaxhHaRw2rYJ1K7bPZMv9OWSfaRq+YDrarUPB6g+Kp0Shet00PrUJjPIRsiMLE6B/3IMfHbxSdS1vzkZQbjazeJSZ/HcrkkwZ8+4Q+EasLjsFebQSbe+AKLsN/vdLRPN5oBilXgDDxOeLGp8MgLuJYJaEsdoVL+j9TueQkX6xiZ81vG2Q3LdBe37PrcZVA3navgCh4xGY6KdYHNky,iv:+vSbT/ZpEhqHCdB9TA62HnkIV4IZg2EuS4E78uPiBYk=,tag:hJ/xrkf8a9SexGp3sC4bwg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIL1RWQzBmK3YrZnA0bERV
            eXFnY0dtR0pYRlNCQ0lQR3pYOHFPRVZiTXprCkZtV2xaSGl3bEJWQlc4L1RFRU5a
            eFh1dFhEUU9PcHRQMDI0YWk4eTh6VE0KLS0tIDN4NDdUZ1pkQWU0dHhEUTY4K1Nk
            RjBMUXd3cmRhcThFZUdBQVY0SjZzdTAKrHiO/Lmfy56RTdTg5luktya/opHr7NLi
            k+4qmjzX2QRAKamZMYuagedgV/gK5mA1pxyJDks9nU2kLOEPq5xolA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T22:19:38Z"
    mac: ENC[AES256_GCM,data:QbTQUSAX3Tud+Xf8B/Y9voLpAr+FFEyAxpqBwNGZNv1ue5viRIyvcf/d0VJFb/VvBpHOwO4zxMHF/jjAhx+2peTUW+OO0ge8dIUXjLYxTsOgPfxtaHgx1DVRRP3Bpy+IA6QCLUBv+75qKMP3BFElBADuNhGaZOaQthjaS9Xn6gc=,iv:RAIRNxlH2zvJshnc2n3s6NctHJBj2KLrLcu25PIrDs8=,tag:YnsDPvunjHtjNI6UQi/YEQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
