apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:bWKWX91Bm8GacJbRZGLuuQtGwDWq+J0l6EV6QIbHNSkw/orAfqTByR04B1Rx/5fwEdpnP/KZmiUjflPeyq4WVra84/YGJX+ZevgrVPBVwfQNvRdx5N7aHaK68g7U6YCVG61CTl+B5pCTcspY7Cs4EUvJsXvuaI4d23wkSxLBd6+f9/3Cqf9QkDlOtDPpMjvmpViSmwRdjWaTFTiMRY+IHbUTo7xA2tuqcFXRaYHe5A309K2iBtJDwPuZCAMdjwgwYMdjZm14L0A7wds42in7eT/2uZVRk6t/X4kNSnA/x7r0OE0fLLmw7LFnQotc3Iej3SpJewVZ0G01UgQi6Wc4ix9HHHx7/L21XbJmhPllXNshQrflLbtjcsI1z7NRUQqy,iv:8YM3sy+7cTW3R9Ag4uR4gGlixEWMFBmeLDGA3C0huX4=,tag:8olFFoHGnI9wLLpgSVyzeA==,type:str]
    identity.pub: ENC[AES256_GCM,data:rcmnJbHwoGm/boGk77LMGQxQcDLn5l8jj9v+31G7OCggEaVoZEw6X/uHYFlnQ1Djd5g2m7Zx2KHZFNrz6oNxnR7rpx+ZbAd1UH0g0QdLw98AZNGEiIvlqwsrasLQODGAlaS27ghWsR1Q6+Aj0CJcU128+wJXjO7jOznEsaGrN7QuRiXkFjPsOy91H+Vc/8IrUSgxEZ/sT7Jsw+pA6Ttl+LWHNCvdjxLAxF7VAIHEo3RtUYpqejcXVNIsanJX2wGBh3gJ+w9eLHI7jE2UTw==,iv:qwkLqfHKWxFbVMVc26tpTY3QlRu3xw4QzUT7psCFHh4=,tag:sR8P8Dr8QtJMRSWYk3cd4Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:1bGMD1feEBvN4GDgnD6XUB9qYJ93uE3GBmmJ4FpvfVSR8QJzrxv2b0uVX3K/9twjLoNJw+Q+VrX8tNA7yNVhyZKkJuWoqHR7ihQ02ZuGIaYdyjoOChe2VAJeP1HhUSxVwKXDEL1SzFkLQ1rYlp4ab1vNjBBKiFbY7M9cq089WIHnIfGUZOYwt8NjigiTlIjmSGa2Tig58vmDa1k4XcDtIFlhnuErsjLbfYog,iv:knu7GQ9nLGN29CwK8vAGNPRRKtVMpCnnJLIPHXtkMHo=,tag:X8ATCEw7TRJb+jdcbS8ALg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpK3BMM2k2S3VuRjc3ZXhm
            aVVBK0pHSlNOQ3d3SFVYbGx5ZEpJUStCK3lrCkkzdWdZbUFZNGRPbHpoeCs5MHFE
            VTlMV25KckowbmVpL0EzcUcvQmZ5Z28KLS0tIG9xODIxS1VkWklDbUVxSzVXSEtO
            UjJQdVdWcGg5NDFMK3d0L0hEck53dm8KT0xNro0uxvEHLriW+CzuXwoYiTikB94r
            pjqU+pMHCbmMCVGAae+3jCJlgdj+ztzk811fSSFI49Aa+wRET9yzzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T23:11:31Z"
    mac: ENC[AES256_GCM,data:4xw3J310iPjlqaeaxR6q/Wsy+KNxNJs/M2VOkdoVfeKcR95/hTVPOisrPUM/Cs1t3Vdbvak7DdmLXcjmmXE6Zk272oW/7+M/juF8iZMeNqM0CMUPPcPzLLYjGJ1y8AWL694uGO9HDN22AuEpjUoV9SDJ2jm1JdWK/Y1u2lqua10=,iv:XhLLcapZMjTJ2oXQ1UZDujj9KAKdg06+5QL+As8u1Ac=,tag:coL704fsD4EpiYFr36Ilgg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
