apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8NOpPZCIPSIJ79oX/ApOe0nBDbLZE46c4xAlkeppsxhAWLut+Orc3kNLt3Eh65tQ34ACGGEMELWgO96l7L6wYqUaf1RbLjFVGp1fG37wwjH3ltWODdeKdS1lcA1ExPYEWe9K16Ghe1FG5YZbyL4rkZx7V+mQoyOIbMTM/YPoeJozmciwPmwqQ8U+ZeetnN0TsMvu9PVm/wqoCGrvlYBUVJY0Aa0E+zEwaSO54nzAqf1jwAlxOInKkjejnaAiQV/kJEgjA1M5JlytIkQRcVeiAuuAxhx/MrENjC4cwPPQEj4yCb8rUNdnmR+/0TbQRjJW+PDzcsYI86+aIYYJYdm9STHKA0s8qNcHTFYiqD8TE3BjFoqMdLhJKl5FIN+yPnML,iv:+qLlVSSEHTobOn6fHE6odVuyB6b6oCYzDiPUieqQM80=,tag:a8C8H4WaolgYWOu2gkyA2Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:9XpvJF+KmqIrZt3mW47/znT1OaSlBKv5ZmdRq+pD+2oK8/T1zyclM4kagv77k18U5H5K2zM0bU3i7w+rDQb82ZrLHfwkG839jmetWE8oqdVPD9yUIuRPUF5UngqAXS1YOqBegjm7hdO/NXGUyaQrdN0m6kXkKlLp5RMP9uS1nqC5zEZlWY8+fMsCLKg5cYyRoue3bAxlfijOIrUDN9aJts0O4eHvYp8x2Pm1eFt5iqr5a9w7H+UABQPKgMwPuW9xPOHfRE0MLOhKInaFrw==,iv:Tlpt/xYI1nkYMHNjraTGWxgxfywL67kW6QPnJEje+ZI=,tag:cQx1gquDsovRMFam4iJxGw==,type:str]
    known_hosts: ENC[AES256_GCM,data:/T4Iqw3ZbKuyJW+YkjVQwA6FpGOuPvo8W3dFahY2rmWOlMpgYeZ7+hFLXMmUjMT9afaX79cc6VRwOBDJWPdQNefW2ZW9R77vZEQCSVTpYtIva/07dYizKVexE5XPaLD8eJQF/xkOWmzG3vTt2vmlTF6gjcqDKlsyf8sOoLtBlR9hSTovNizdyAh2V55n7i5rYhbP21EpGDBtiZeH7JZvhzo5QQzle7Cu2r/d,iv:hTQpiuzL2KfpK+sIDdoIxLugxKGzMpnkoQlQiTMFjxA=,tag:WHuYK1DbFojVlJGGhNougQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVFZNYzhrWnBJYkNISG4x
            Yll3WDBBYlQwQjNGUGNBSlpOVFNyQVVhamxRClRFMmxacHc2OWcxZ0tVTVcwaHhh
            b1RqUkZOWXFZbGVQZnBLZ1lCU2JQa1kKLS0tIG9xNDRtaGo2dnFsSHl0b2R2SWtz
            aWMxeFFpL0dZazN4bjdneUpacFd4V2sKsyDbL41XTOl0q+t1x5eUzg4W+WjgddyS
            dRXDEp1koGhRS0fn6p+ZmP8olwzWGIFLpfqjjlvFkAsP961y0N3h7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T15:48:55Z"
    mac: ENC[AES256_GCM,data:t0iydDaiCrn3DkO6HDDJ1MY6PGLVyTG/HQlL+Skk2T0GT/bEQtpajqSGp8z4tjHI4zqVDrwyIKfEg/0VbL44Ol2htZy1LhQ1IsH0GjrQKprUSYXsFz36+AEXgh/wPEjM1wM9C8ZqH+MnSBhluoaH14/UV53YuXCM4SFrzWZjuIY=,iv:QwRPYn09FTTeCPVUZB7hWyZhpYgP5YnLG4D2jvU6HcM=,tag:PJKZWzDrI2dzU1y1oA9HOw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
