apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zmzuxeticvXWqjLUtL/kSoKQT+mb3/Pu4bDN38YtB+fVYDtpjIJ3grid1KL+FSnWtisrSD42VOituxCBSdEH5PNEnlgn7Kk3MmytAMhOwxUKXJo215izuku3a1J91A0RV1XK7TND6KYpHASAO1lFGyWdUIrM2fsl1x53EvLNkZ9f8ffMMpvjUjqZWte24UGOC9MQ9ZNspitzhIr8j/8CklbWtRdq2fSVD5xD3u8x8HQNKY4QOloEO/KGzTB+kdd71rztijdG1IyxJ8APHhYpDRB2wvsB+yp68V6et0PclEZjcux7kvFLUzEVWyRGtBxy3C/DHjLBVSCNdaEYHzUjpVIndoas62zRBB0hI88p0e+anbEhaBpOM3+c7wTx9JB6,iv:b4GOEjqNax9iL8CACQQuKvIyejl/40O8wVTBMgC03sE=,tag:Lbj/52eKc0F3AOyceOMyVQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:eLG4jbrtVF8sw7B7yn0h3zsIM0ThCy1QXCS7poMCbeaCJHN4ZWWq3Jeisuf7LZVgudUriILq6dwMYHKW/3c2OrN6JVCSBSorqZpeq1Eax7lzASWUics3hktL0Subf/AFHKicQuXpSo/Ab5QM1bodHcw6OIXqQ0/KwErQzuzo05zXGSyyAESKkSEyymLC7ubuPvVBaJQlo5P3PIJILgZSm0ZGWv/z3/2qgjb4eEkWbZ26hFFurvry7rO4hkrqqYnnLCMd7MmxXMFb9GOctQ==,iv:M01TJC4GfkODHMUACHr2+5SUQSYulbciuadhH/UhVfA=,tag:S+dd54PvargVGszmGmiFAw==,type:str]
    known_hosts: ENC[AES256_GCM,data:QK9vCECLt0IPKvsGzAEFJPQzSY9TqBlhsSU0q3o3zOGbbYIDpM/Pm6Any+F7U8feTbAmp4bjdHGx8bgwu0uOhOj9L948E9YWscjMh0w7n0QLcoxMoCyNc+fesm+J++t84Qfb2mB2UVANIAvlHLgmF4199T3l/lTb7QMbtJydXeTawG5OxRSGI9kyXiEER9dMIwpzk4R/1Ixjv1IZS0y5H7Od/yBKGdOmKeJc,iv:/ASXgkqZ8Rp0/277gfZRGb+oT7NUmthfG/NiREzJpdc=,tag:B/1tZQ53O/wftlklwq7Npg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySDE4REcrTTVFTEl2TEk0
            SlM0Y3FYRTl3YW4xbnRoaHhHV2pFc0VodUJVClA2UWxERnVlRnZqaFI2dDRQM0dX
            SytEdDArWXFmN05TRWJjN0tjNVArWDAKLS0tIDQ3eTlQUWdEeHE1QzZncnFzWWZq
            WFJGZkdFTVFLUjNJcFVYbGtraWNBUUUKsTiAvzjOcsU6uuCQt85U0CZ7aSLQpDMj
            pwPsshhERRkwXf8cZCFP2ealw5dppPUacVaCPGJY6/jotLs9gaoKXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T12:49:32Z"
    mac: ENC[AES256_GCM,data:9PWz4A/IlFTbE9zf2DyBZ7YQYNa8gBgiLC4wU5WsStAgaMFNmo40+cZMgr06G+yci99h6jLbN3B/v8cBXGMietIZBmqQnAL24WsEwNqA2tv9nxAjFcshRnkcBMLunpw8y3Uaqp5ASZE1PNlk4PkmpVQElO/Ra1vPmRytqmj3p7U=,iv:nOT7KiWKf7OaXj+Nf1SBDiqThnhSaPh1Lko5e4tajzY=,tag:69/CkVDGph9Ja6JTlNRX8w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
