apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:tVw1tPME1HfyKBysJEFsY4JFMr8Wumkyj1/mJnLBSPJPZ6VWO6N8sUkKLcg+98gx6seug1HN8LlzWOUolMCwCqCvkdR0mNcqbT+2Bv49A1DAzlCP8yBaLc8jsC1GEH20v9QW6uvjN/rmtZu4XN+SPHJmOwTHfU1MZw==,iv:97j8+98B2Pm35luTlzLJFhSSZZKg13EQVas8vwxgLNQ=,tag:fpqzaOwccwBQoz+OMO0Hww==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUWdPZmQ5ZjRTQ1p0K2dT
            alBHdzRCYmh2UFhJNzdZdnU1TlJOdzdYN1UwCmJCWnlFNVduSDhNNG1DRFlMcnFC
            SFBxMnpaY3E0SHRXalF4SGY2T2RWOVkKLS0tIGVZTm94UjM3QTFQNDhKWTUyRkhn
            N214WXduTWRBOWxIdHh6ZjFWZzR3ZkkK+jFes1hHfP/CkXqzWvduQd47Ds0125IY
            VmdrBvsxRycvWdYKsNJJgmqgipmbn/8mcfoutPwMqCWfPqy16OIYXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T20:53:58Z"
    mac: ENC[AES256_GCM,data:+mFRXte+volciwJBOCxc1ftQ/MJofdTz0ll5WNrhFb9/9HpAvCVzQ7teOH/JCRQz/pS/9yI4STH/vdgSCj1FMuMb1km77sOJTPEHKXK5MDNr9JAsxM0n1CAtSvWwbwf5uXXbYgMvMEcAoQPEQuk3o0ZKJSX6NmBy9wi/qKVkpEA=,iv:F4fAmr4xEDqrC19mNRbZeFQdsDO2f2vGPjd6cRrp18I=,tag:U51+AEpWnVmQyawrE+wMJw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
