apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:nrtYoDyQjkAlh6JmUu4tmpYafN68wpaHnp+lzDVU3PQkALSZ4lW5xsmg42cSJj8OG1rBwZQd8fMVukzSTkTkEb77XXkJUHnOBPNQWxWbA5hLCpFruq8U37/3R1Wo8AQBsRj3Zs5dcO6xtjDgxsB4/pI3hK6r5JMMPA==,iv:/qmPrkoifh75hhi69XjeZhX5v49MPGoSfbPZbccM4vI=,tag:DcoDgUzUDwWDXaSWIGrXZA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSERtckZWaFJrY09rbEU3
            amNXb1M5SktEK2hOYnVCTGlrdXJGWGlPU0hzCjNMQm9mRHB0SXB4ZmdjMHlMSDBj
            ZXFlbGxlOW5RTVBQOXQxcVdLWTZkRWMKLS0tIEpPOGxqSy93M202U2d1d1NLK2RT
            RFpXL2pKT0JJdzhsaDlQck1yTG10V0EKDR2WL0svcQr0p8T7Sn8Fas7L08n0SB3j
            4E4p2h3t+oE2erZ8s1kvYOLZ9g9U31DbcPv/HeH559EiR6gz6OTHNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T16:01:11Z"
    mac: ENC[AES256_GCM,data:7Pf4uqHtAOAnC2A5UGFHYFvxBmCTXy3XmWn/PIixsqNo3i4nwRmrAVq3wXME7S5U10R4ARQIY6h3T/cHd6uQi+09jDoW8FxXttvpjf/okVw/TpA94Km+TCX0ATJy4NE3Oq79Xj3pLtRfEeEkVq0q93AYjdYe8rDRzUbynlWRs8E=,iv:y0dEUCcWxzbzXHDsB1Cokpq6UOj9MociniwpWZieuy0=,tag:IWQjbBt9ni96CnSBEwHLAA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
