apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:znj6b9HccepEpphPoqTxWHrHzLXSOXp8j0e4/J+o6JiWCTxeeeWlFaErHK6AUdsz1xIEMiMLadpBmnfwQnQgqrE5BOilSwCbtEWHqZgtB/+ZXVow4Ve4Fn2WlSmg+dN2+dHidVxuPDdujWCVDNVdixFHSRBBqXejUg==,iv:8lc7viJSVJB4v2TjZg6ZUuLDmw8TDdetbmlhsFTeUBc=,tag:XBqZj99CCn5BD/ejLLhaSw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWHZqWm9seVV0UThoRW5B
            dnVnaUduUFpvcmlHSXpOaUNER2p2cEdYaWdRCnFleGtPcXVtRUw2eTVtRHJaODV4
            TWhrWjcxRkFDbmVhekorNk16Y1NEOW8KLS0tIEp5RlRPVWJsMDVWQS9FZ2ZYRFND
            bHhvQWY5SzZ0WVBMU1BMYUEzNkhLdzQK5aHrZTCl37zJHyAHkXJiFi2is33JAvzN
            VNa7F8GRurqq+PK2GxhzFdoyaLIRozNt1d4NlORhIRf+5w5imLRAeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T21:12:27Z"
    mac: ENC[AES256_GCM,data:blr6iiSeUGK3bY/zBJaHu2pkGv2jPFF3vceCql/7gWspT60ibkTGoqISXCup0hUfQp1DE/i/lGerUlxHyNX7Ybep91SAEx70dG3QXeVOpF+vnZyKsGTah5OxrVWzKmv9cXczoOc9E4f20fIij3RmiVXsUsPtY/ktstdJHFCfAFU=,iv:sBUJTyp7Kow0q9Fx5MESrvdIxyXI5RQ0NOeULFw4mgs=,tag:bmFy2xopDVnvYaV/eZHKqg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
