apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:1D08Qzdhr3RKt0xwc7IAQB+AkwlpYPeaMNrq0ox5SPyvUS98slUNZRgCSyXwpOELSrpwfwQzH+nDE8XMiHfHANY15P2XE1otErhLVyoQwGJJqJHQmCqJSWpsuh9OuWw3Vzx/6ac5TAQ5YlYycwaQFZAAuNlT8xm9Mg==,iv:2dvhheBgkzW4CKR7ix+bTGk5VL82Y5KjULKLbhosUOo=,tag:zSoMlH9NEqbsXB0fci5KFA==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:XwVJpydgWf/OSkRDprbrQGR+nozimxG5spyz32wViBEiWHtSst1oVM8J3XGiYHjkAcdLFe4kCdCtUb95Dt1n1w==,iv:HVhuyKB7GjbOE0kzoHbW6SYFNwTenJizoz2uPZo/ut0=,tag:ghn7qatQETQN2kB3TJL1+A==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:5AOpDGiTe288NqVH8Y6zUYJXKwgyefF+ZwzPWsTvJzI2FZKoTdBDVsdtK730yPdqMkDHe6+1C94031deaH3ZfaCk0bj8x5lEGM9uRar2Gh3aKzfKvuQK/xrRl5g=,iv:FYNXD9khYV/Zgk2kv6MKtmaLt2c7khR0yFrbdOWnVic=,tag:stjMkXgWOdqBVwwzdooebA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQUk3d2xUcnF5S290SWpL
            cml4SzF5M0ltTlllUUxSNW1VUU8wa041YVhJCnY1T2g1RENoUUxxWG11WlpjbHlY
            cmY4Vyt1NkNtNnFmem51cEw3ZHFacm8KLS0tIHZaazJBOGdKQ3RwVVhhckV5RlJX
            WUtnZTdrYmpCSmZEWm0wTVNvanYzUVUKJHxca2amaCtJ28UIpzDhIJAFoDO5l3Yk
            bh9cagkHjVQNl5Fv4aThSLCmyaNtFfwGCGKcPZc0+NnSrsXh8Xh+aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T17:58:12Z"
    mac: ENC[AES256_GCM,data:HEOC1sxlX3Fs/RWtJq/dJwGSll20y/ZxB1fUw7lidTVnUCfXrxkPbWWkyar4lxjjoFJwV6UGsfMxGrzdSxr05N0sxN2A/Ag4yocwdPfQbN3/1R2WzsFQGTM84bQXHXL/zde+mYCiRrTQE0UofK07HbbOt0M2dhb3m/zkBbcqaNg=,iv:X1Uvw9iY5CTucAALluXuHHGJLinTygTq9iShm4OOkd4=,tag:3nauNMlvBdyVA/tR4ckRRQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
