apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:Ld0oJr1053MKREB2TXb4XOZVvfHKWIQJf2WCQZMuZfXtoBHnDbK4niSJZYxYkD7aNORxFlftufwGn2lkpdS/GCUkfvQRmUSxORllO6McS5jr4v2xCRQAbDb013xHVMuE/yRzbOgnVftWdWX4uDuEa7FI9po8PbY0yQ==,iv:2GM9u/3eqw/ZWpRVX82GXNISz13j55ERWGjFkRMQlog=,tag:4G71sz7DTW7SiTE+mxwbMg==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:q7qFC7sew9USvWoaNkZBwRjFh2TPunjfbefmV4FiqAkCiCA0yxn+Af0PlHTwJRT0bV7Z/4AHxUfOiXpixC47/w==,iv:EVIH4SAEHfCMw16w2tMXBCH7wcJ8NaUvzrxpj1rWUOw=,tag:okCW8q6GW+TL8ogn/0cCeQ==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:0UmL1F24vXN+EGpDCmSyb09tTUGFrVm1SiE27ZrNYEfy0BuVn1mSfxy6fshWLttH+qPslJ2EgfLHXilNNCEsNg5VAwOTA9zofkAZ/kepCYZFWUKN8A5fVIU17eE=,iv:DgXZAXN23YU5hxdr6SxvCB3wD2fjLaBuBVCHX3Wf4/0=,tag:4CAuFEGG994XcshjvMXm2Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVWNTQzBHTTJRVHBaWnY0
            N3RzOTgwSjJlNDhyZEpFeENPVzFlN3ozU2pZCjVPb2hBdjJRNHNTR1lYNjNlYkRj
            dktqaXlGTGQ3K3l1VUM0dGVLekpabjAKLS0tIEdWcE1mSktvcWVRZ3djTTNyRDd4
            M25pY3lTNGI5ZS94R09sOW9QTUFLc1EKHS6P/oPE113s2xyfffOK9pe2UT+UdXC8
            tMjGLWJHGvz1vGLNQHmZpzbqLbON2fqNWrcSOrR0B/9unE/BfseWaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T17:32:36Z"
    mac: ENC[AES256_GCM,data:XgU1OalTSURkrPU73GpVDj3aewZgYARJjq9K6Mm80TZcQWaBqtBdbOpGM2i9D57rYX/g6rXY71vKdPWWd48ouLtqoPxpI3TLtT3ITWICa8a/vy8zh95j1l6Gpukb6yjvCGJJbv1ghOjm5/kTG6I+ahfubo49RztN0bUhDS4aGss=,iv:DZOLBiEascMUyjbTnflg4MShBV2CLDy8je2iIv01M2w=,tag:+bh+rjR478trGSraIb9gMg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
