apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:yPcJXomBNi9I/62UHt56ooOYdw5nIGj3q2nzajWg9NHifkW68BKfwP1MMCbgzU7o0RAK3/6h6Z21n7IPGKIizzM9kvICkbskh8DYbUrk4Cdou5jI3gvMtpgARopZ/6eR8jACDwtksiWt4oHgNw9L7BtE4ct11FzTTA==,iv:sZqr2sHBwzv6Bc9FzeNgjE70RoZepGpxAPlp58hClec=,tag:azafMJAmSMtOkuR6Q4aVNg==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:bkl4CacoPyV8sX+FRQ+0wVNSCMFs4pwC+WCdzm817uCVNWVO6x6sf4V6k6E2xBosa7HkZwaoLyxzQ7clCxZx5A==,iv:ki306kUCmaqEwmowD8BPJlRmG2Et0PxXk1sgxqMCVJo=,tag:P55xuJXJyb+tUapayHsjQw==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:pZcOWlKXYmDwn5emHGQTLXZLvXSqwmN5G9SsqfYefg49KlUhBI5ygKG/ZsPt7LuUcnYw8g9DINC/i7I8A9dZWGcTr9Kl/8NIKyhuPWT0+qzudGue79KXZpJqDd0=,iv:/Cj+uoakARVoIUPCZMiK39+p3ICTClWBTL7TgQ7lgjk=,tag:gzT1MNB88VT8f063JwMGog==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVWUwZE9mRmdXbXBsS29Z
            bnJudVl6UFBqbUpERWVPS3RTeFdlNUMwWm5vClNJZFRhSHJ4bkdtU2lFTms2OWt5
            Z1h2T3haNjRRMkRJMmpDK2IwM0N0cEEKLS0tIDJNdG16K3BHaHp4OTBZU3IwTmxU
            Zk52aVB6RUNhcmRMN1JEUDNYVTFpTUUKipcX2qYLU3jdK+OSSvntYsYZmpUduZxN
            vpd2ZTQcIpLurUFfuaVq/0ztySFZE+RbQx0G4MoV+rDh5DSSQ68ywQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T20:40:32Z"
    mac: ENC[AES256_GCM,data:1cmJnVeXoXAet/noJghC1wKon2G8muCOi2TPo/4v9whsT7m58ud+QaDCuNnXGFEJzyooKbciZ7z09eFa7PjoEeUatQPOFptaPX8CQ0hk/IBVtdf8BwTv5AmKwoS6HoqwE3bU/8qBx8p6t+ONjTi8p+nx58LPHV2WU4W3id1/pCs=,iv:H3o9ZwomskZKjL4rMPWxPBEnMhVHK78hLSmzaeSB8ds=,tag:SfwllXvYvF06A39hldgj6A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
