apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:di1WrWdJjgkvKdkEpG0+tI0lZoqwAZ7PZ9WHKnJstc4NP/UIXGCrvjkpGa9ipozob0iKgqoL6K5PniDIdyCPfK8G2iZx+DQ8ItVF7zSbv89nTVQZeC4gPgpQuckkAPM4yxBgrpi0WXLtKXZ40x6pRye9ZwqFuvBRYQ==,iv:waMR5JchAieWApIinwzgRyNzdfMVLxODWsyvZI/X1iw=,tag:mkCjkux7arP8st/Z/fwR1A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZUpabnN1R1diVFZvNllV
            dndNNSswT1M3L2ZVZmlEZ0pMVHU3MmtDV0Q0CmxaVzFMT3pYWFpSYi9aMkZQaU43
            ZlBkeURYa1RuSUhncGhHK3dvRERLc1EKLS0tIHVrcGpIbHEzd2J3N3dTT1N0aFNs
            azZMR001MmNENVh6YUJzQUx3aldVV1UKqxn3mmjOCzan+2Wpqgj1IwnVdsq54Psr
            T+X+Vtji+yG116sTX7qKhJuhhBOvBUKYu8bTZjGqx5s7bGoM4HOi5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T22:19:38Z"
    mac: ENC[AES256_GCM,data:PmPbG4TerD12EGDz/lbMUxtCNrTZnHPSY2Cp2CNfi7cbFZEJkhUTXRm2xBFCujzfFOTy0lIryC6ReYnMEuFOt3/ikOWaDKFiEnO50ZMk+AqrsofguIPWcjMZgcaLVJiOEwQbefRq50cpMz6bVhboeVu9WuxtL6g9oQW+5AknDJY=,iv:HjxEsf9WXFNLlV5dh/Lckbu6T03tgJwuzJAaA0PJsJk=,tag:xVIS4Ij/caN/qZICQTfP3Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
