apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:+PnYs1qfEZULCEg8sN/9QcyqDSOn4pqB31q5WEw36H+m7cwmP1a57Rw5vCUDCVzM6KtLkQfWDgdBDCoJpgH0viQe43Y6ntAlM7+DMobSrqQcmwDB7NDZgPNSMthgHemqCOb7aVV3DsOkLP99IqVh6p/9BEDGHaoDHQ==,iv:hFWpfVhicejxcZtEdIMpevG628xnUnR8xm2XqC6A9IM=,tag:xqfKh9zLEfO9xgdts6NOpw==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:61Q+RNUoK+0g8LGL29quiMFm6ysAMNB5itC6u5cvJndpdZjSbgdA2JIx1Fxow4a7A7TrHw77PWa2Q2d8e+uP5g==,iv:ir6SIx/7XVb3nldOEYLTWLQCXI/A2+ggVilD/J3c1po=,tag:DODUzTTfRSdvvCkXftRuNw==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:2BXXQbtZn4K6pV0OdULXe6u4BrTucTzA57werK070F09gKQlArI4Ew1wNPuHN+J+x71BsiR1e7nPQGTxjvObMnvGDsbfN8WW1YO3bPpvdv7UTgxpyPa1v+M3EJE=,iv:2ozwn0aqZLLG7JNKz9/N4Y8mbdoVhk+xSBbp+p9vq0A=,tag:ZimIg13PXICJAEYMTSdxbA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OXVlRVp1M0tMT3BNNmdJ
            dkFXTVRNOTRJWnltUWVhRVlidVU2Ylg2elJJCjNVZytEMXFSeEFGS1hHYlJNTFR3
            TjQwRmJhRGZFRGJ3UmFkTnlFQmdOMzAKLS0tIEtuSVZqVUZlVVhqcHN4WUE4Tllq
            UGhNSHJFdjF0NkpEODZqSWVPd3NYNUUKtp4ehw7Qf01D/LgiffLWQU5oa0S72tdH
            a98Vyk2VSUeVmCxKMouh6AuJjRAloE0T2GBwcseBwhm0Yd0j+zqU+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T14:49:01Z"
    mac: ENC[AES256_GCM,data:/BEmCWd7+zlUSn6xiA9gpVT7lGcfryw6lH1RjgshJdm4Zy0PX5tTGber8NUcJJq3llvK8gRUrR+EGiziw3HIGMAIIzWQVvxkdxXTmF+RZyljrzEtS1+Cb5xAXe5MvhRUvdjjLXcRn6+4b32p0z9x4z5xl0336h8pDdVCjmX53hY=,iv:zhBq/B5QDQ5Tjp/bxxzrQZ8AafCUUtAORGh5ejgVDFw=,tag:E1miUy4m3Y55Vepve9inQw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
