apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:bDm6lxKnBBARZ2OFUsFrLi2/aQPQzlkxOSnBjj8x71RLNuWV7adaCaW7HmboHK0Ruj1eraytFUfdz0tsoxDeX2QT6Ky/euTrPvOZdCmyeRPcCAdLHeEIcm9dTFPN81uM1HhYCFyuNrtFTV+VzXOOIrxtafAqrMrKzw==,iv:ykmsXuaZS2VbdOF1sdAnXV2y8DOthrrL7imfsW1/IfY=,tag:dYPGPOJAMbIuD3n4DOgPhw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSTl6K0lUUG1XV3ZiNjRI
            VFQ1SllvV2h3VnA0R2RjTXhHY1AvQmNWN1RBCjNjUmF5Rkx6c0RIQ3IvSE8vanB3
            WGg5N1lWN3puOEloYzZuYmhXcENHSmcKLS0tIGN6V2wyZllWZHZWVFRvcnh2WEtJ
            SWUwMXhBd3JtdkNreUgwazMwY1ZmMXcKDS/T9CsK0drq44yTZ1nlLGUaFnYUl6Sz
            aQ1LzhNPuKrzlYNqPgzASX9bMVXw4Qp4gB9LCzWc8wysJw9WQYi+PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T20:21:36Z"
    mac: ENC[AES256_GCM,data:ilfe94lp9CK2VVrc2LnlA90Lg2Lsp8Yg1djf3sWwoY5xXEAzf6eg5Ocb/xGQAor9i7+cTyO3zBTigeRQ4Wh/2TKHAlPrdUn8RCA8DZ7MVor7EtxeacnSrf2MzgeIhHwQ7235gK2alEdIvIKl8nFy5uHi1CgzZp684XiQsXnZd3Y=,iv:sKoN6lVvqOj4hM63DkWsu3E4fsaBO/4Ns3LVAxlXWm4=,tag:Q6E6IAuQ0ySMIXnnqW464g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
