apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:I4Xey2DjPgMGUGX2nrMzurhl+ytVu3IpHL2lqJhAVVST2W7I+aOTBFlvB1exk6VNsL34YaatVzREBBVRqhZENyajojyJDEIPGBpCtNaibzfyQRh6MZZR7eBhy05WJGFXTiJMjsKJxXrBw9yCH0G4N19wNx3Em7S5hw==,iv:pCPu8awnlC1mHoL/zFy/+FjcCkkmPAWn2L4adzqubpA=,tag:fXTzWJiGjcJ5Sh3n6c+lPg==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:Ooe+r8H1TfYkNUqQzpLRrOoFNbV++apugaIKZmiQUa+pL6zDTVi3fgAEo/e9FBiDSeXy6NWLYJC3L6B+s4S3yQ==,iv:uoqBNJB4Gb1iu1dFQDwyTCgqQ3k1t7FUCD1I6LE7sTk=,tag:mz8d7y05lh3j3Bxg7JmqEA==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:pMsYcwbyagfrelsJdKI7acDNbHunzoEd4IbKOemRBgM/1SAkzVqZOighIA/mAtSpxmMZSy9QwwMY2JMafw+dyY6APRTv3QqOt5ghbovnoUrkA7eTSxYNoYPTqt4=,iv:zuyu3TEskgB3Xby+qa8992WTCSfrA/N7gSzLLzdxoPY=,tag:MT7ZZOVKZzVIMkNoLjvNEg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnV2YxNGIwTHMvZ0dHUXZw
            OFdzMGM3ZnBkemRtcmp0RC9SKzBlVDlRMzNnCmFOelQ1a2hnMGhyaHhHRkRKV0xW
            ZGNsQXorQ0ZqaWl6ZkFZT0Rxb2JHd3MKLS0tIEFDQ2hKR2Yzc0tlTWpHaFNkb3Yy
            RzFQOHhFM0VJZ0JDUHZtWnhpMlh4WnMKWdj2v/2NjsGQqe7m9+UzSEz4FMk1AK55
            rq7tKvHSZ+Y4mf3mIPbF8yDpmZR4c1cMMMTDL6/XT/81TMa2ZLQ4qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T12:49:32Z"
    mac: ENC[AES256_GCM,data:hN3zgQIMTktFj89odeINW26md6td63ATUqmYmg8aYB7s/i4SQ05QGsdgVu2xIzD0ODwVQY4qVU3WiHFe8wNGYiWn/22k5P41ABolQz80/07udiwFTGH2Ow7kApHKdDbKHaedYVfVVp2R7uymGatwAUNG7kg12VwGBFKfJTW35eY=,iv:4HVIaMQs/YaRze0kpDaCiRa1W0HVdoOHevNGvvjJwuc=,tag:34HMOrGM+m+g9+eko3nzbg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
