apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:PJNEzunNTyvmLuHIwGPbCNXUDM+KVfAu/OiI39Egj8Ocw9OV3iNIH1/Crya1zHdNPQejfEglRpHjygrHqqVQ2mr2hsgwkO09EYGukWyDLJXK4dHhfuWAbPJANUjO1rb9FhmRJnFeGRT0bXwpOZEjYK9tn/KqckxIRA==,iv:ifhVzudTx77gspkmtHcwSpag3XXNhAajDfaFaCUK5qA=,tag:xBWfnfOLDdRstNApWTKvyw==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:OVmEdQ9RNWFQ2+47kz3HmK/VR6afd04wpK8Bo10Vezg/Q/at63cVcIkYbG5MOYG/9hvbJhnyiPHFuWjcITcFZA==,iv:ud9QTPfOFiIsI8gymPUZF49BnuEaqF+WjJ59t2KkdoU=,tag:jLu/WJiXgNCZ62qnQeIP7Q==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:ssq6Pp758WOVQugim2eCovLltrx7n/Sn3fN/u0BODObOeeLilNduJimTUh73cmMyAxh7sn16v5NSqLa9pPNhVBR5vjt96O+a4A/+BJoOLg/TODK2HhnT+iuF+F4=,iv:fI+e8mit+100dVWPVRr7THQbPwSjMB8vkio2wnI+ODY=,tag:h9cB+QJLRDXvNCrM9IFD3Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WTMydkdxVzdVTnhUMGR4
            eXR6bHBiNjhpdktic29keldwZjRpY3c4RGpVClBNNGpqQmZnYnN3RzE4SG9RSERv
            Vk1SR0lIdmpNZW9keEdEQ25ZdE5OTGsKLS0tIExsUG1maHZicnpsWHN4SGU3Q0hu
            MUhQVWo0NjE5Qi81L3BicTdKdEZST1EKGT8AYyTsDOtTlJFMmCQob76RQHkonqc+
            Q81M+OwoYHdxqGZLbLP4wlpV53S3Qip3N80gfklTn4YlLFLMIdc8SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T12:49:40Z"
    mac: ENC[AES256_GCM,data:Ap7JcyQLfWwdYqBEzr9p4CIcSlWQuTFUC+Lh1MdUT6bZc/iidkw0tWI7lwAIl1+3HpRZTWbqG3DFuIzmClQ6tp+r/1/jiIOSqy4KFb+yZdYtJuLHyWp3p5Zh9hBcvvf6D+lVEN7Iv39A+1RheUqWh0subkCYaxSHzZC6DegfIZs=,iv:dGQtFCaiQP5PJ2feqngDilvBifQqP7nuL7UHziI0WVg=,tag:3euhewv5QvQu/2PFHUHlNg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
