apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:eafzdl/VPG98NwCThp/5EXFKuZvTQcVslzwfO6NnfDu5VMq464qJIR3ZYNdm0kYWZ5whTBjj+WrGt6j1mhs7E4Uc3GvC/5ajANKfO2ZRJfpL3VcLfPT1TROLpkoDud+wKB9uGSf0DlemYshpGhEP1G2SUaVF1IgtTw==,iv:W0o7Mu+V/TOA4n69dB8CV/e3ud425Pa2PEn6/Sy7aa4=,tag:+4GUZnA0Zz51w6B2HCZopA==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:9SlwDRZC6O0Dt8GbxUwZM2gd18acapIJCqgha1arNIARcGR0unHCUh9WotdpjWR3HjpM8VP5j4Fqhd3r7IjpwQ==,iv:tsmIvpmn8D1Wov5hY3MsrJk8Kb6NKrWl66iER+g20zU=,tag:LaTgfGtCIAx8sh+0R/ROOw==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:KIQy6sSoyGAe+1kXkSC+2PN/lXOkblFOQTJRr/BwVKnSJ2Bw4MoRpAeut1Jq8zN2XFHGrNj9O2KRfsF2BCG0lkTg5y+YFfzTQxC1j3mc41j+Z99QGTqo+tOT0Kw=,iv:ezxqFBQhAKz4PcBSGH3BXJroJssOV3ypxc3EsaD6D70=,tag:8XHmi+bcVRyks4OFwX7pcw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzME14VC9OZkttVklSQW1s
            WWE5Mjl1SmVwdVl6WW1pWjY4akliMXBxTTF3CitndUhxSU96OTJhc24yRVg5anRL
            bXZyb0tGWGhqYVZubXZMYnpIcGdqZzQKLS0tIDdRL0FXSE5BSjFVampTeFhiOHBB
            YkMwV01ra1hwMzlhR1h4WVhEV3pzbEEKQEYu0pOgt4fC+zIDLTbzkuu0GZh9ECU4
            rPpXjO0lPBfOqCbSnkMzaLYC1zDN/jNkBxHGq5NiBV+htvJUDLlUBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T14:40:30Z"
    mac: ENC[AES256_GCM,data:A4wWtKghsukypYh+gE3WNgufxdJjUdECnl7vJky6iMs0W0UhvEA4c0ikLKfYXO/svub3egpCBo+1N0mTnX+LrdlRNEpnhep1ExBmmf86aM8BhJxNcvcU0l63aylQ8AeZZNnQShffwnhGY2hXd6eN1E/r8ZdF04A3edXK7swEfoM=,iv:PNuwwqCzPPKGk2Uz7VF2KrW6HXjO193Zbh9twB7hr8o=,tag:y+S0N2WrcuQFSBbxH4+SIw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
