apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:Vq/4WZkw+kuOM+DSnfogsdlNGvrug9L+N//wkbqwuWnsmV9pxDvf6j6M2qCFgQDjxW34lc6fFGlkret98P2yMAdjqnRLbU7JV/tB/EsC4E028ElOOXWRg0a9D0HxWWhAOOlaD8hUwCI/1ZGggQRseydR45fBpfWd5Q==,iv:iIPLHB4CGlG20rHzt/9I2drGVXempLfPvpEsdXmVI1Y=,tag:zkBonpp0372r2nOLMoEwdQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZ0w5MlJGTG5maktWZ2J6
            aUpxUCtxb1ZZell4RHFkNTA4KzI2bmFCZ21jCjJDL3Z3bmVZczVRbGE1Ui9vSnFh
            bXRRbmVlWjd0ZG1TZEZmUWoyMlNhajAKLS0tIGZ5QTBmRlF4VitWcjFDd3I3dTRm
            K3NPWXNFTEozaDNSdDJvWm9XMGNOTEkKRitRNhb8LHxfCJoYqDEo1euq2a1NmI+Q
            63W9VPN2S+oK5k2Vhjkjr+eX9Y24RVbJ1GNr3tbW0UPjzINBK8Jx0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T21:24:37Z"
    mac: ENC[AES256_GCM,data:yQkvb/B+hlaFo0gf3QxOuMoUNq6PeGDNsL+q3UTBDECaBBnDk1MY32nItjl09tGJVQ3Ua2JUq+mNeNlwHLFieQ791N5CpCOtOWIoBpwZm2/YZrjft8DwL6V2CdVCoR5AX8BG5XU5EVGzeJqXz7r/wdJS8wYlyuLzfuF7TZqz9Bg=,iv:XntuiBRPzHPXvINquZzDiKfLA31T3tYrXz0iLlsF14I=,tag:nbUVQEszYVYJFdaAoCuYhw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
