apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:pKrc0IANHOt3pkQ20i8mKg+6glmsrBqtdoTMgyxpafhUCMLXw8crbPgzb6n3rc5o/o5u+MiJ7qsiu3Ha8Jg9/h2Y/0YIXm6I2fLRZG673NnSSW7f6UmDXNbfEkqB8cLX7VSF7PlM+w12j5gU+B5gl1T0kD2wQ6wwYQ==,iv:yeE4zjm3SWM6+/11pqK/tGvVjTniyqtOMoZ9reTIQ34=,tag:KPajcFMnG5J4X3NFoPGMLQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2THJpbUNIdy9QdEdMTkpp
            cnlMNUs0WXB3R1RncWlvbDJmTXRqUU1USkNJCjFZMXExRHhFbngzZ1RMaVkzaFl4
            RjJmL2JXamNVdnR5ZmlSaXBvYmZZNDgKLS0tIG1PcDVFb0hGQkZXSnpPajNCaDlK
            YkRsak5aaTFhb1NXVGp1UlNUTU1yemMKm9wYSueNUTStRlbiI/tvd7t377ujIYPK
            nlARDv+DrOzojSHG6yNM+4HwFKxJOqAyZ7/mfoDyvoSwcETXyjTLHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T14:53:47Z"
    mac: ENC[AES256_GCM,data:dZYoVeAyvl4WTCjDi+/IuNeQEYgvCou7r4dqpBYCtqUMVTYRLDbt1/BbpwDhhQG66ATIUlzsASkR0zVs72PXfQp+fv7a1LmJx8P7jdo0YXZmOcO3hs5mOxJtV/p7B6Auo+zBqzW/rd54tTBlo5pyUwwtD/NYk6aoCYSJrx1u1aI=,iv:DjlU1VgC5gXKKGI2cT36k4GKEdWxETvTKhQyiP5vJSk=,tag:aSuQn6qdQj9GRMt0qNvP/A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
