apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:jZ3GraZDpkNnROkz5G7A05PadW/iMvjZahaUJAfkApexLgKfxoXqCldY70blV+fFzsujXCjTkvj50PsxO12Xqmh/BN9ZBDnz8Jk1HIIVbkO70HFuGnY0ZeyCAESHtK7bdgT4QizXNkXd7cyteJpYUKo46dPsxLIIyg==,iv:Uahsd7H+Z43hvBErAlS17+vKv9WPpi9QO8vj8BWSVMU=,tag:kf3QVy0WRDIsArMB/R46Vw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeC90NkZNWGdGZ0JrSHda
            VlBETmpKdTV5RzlGV3R4NVhXUUtvZFBLK3hFCnNtVUtVcFFHTGg3MXl5emoxNldj
            ZzVvVXQ0akxkUzdZRXVkRWdjM2Y2R1UKLS0tIEkrOFdRNEdrMTRjb0E3UHMyblNo
            Yjd5eno2a3dUTU9CclJEZW80SURpQk0KMlFd0a8EdtC8S20PZL2m9/RwvUsiGpUh
            NbD+CrhYEce+qUb8q3kAH3BXwfT5NsIX1cvvweQ5peg+K3JuPAXTKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T14:39:19Z"
    mac: ENC[AES256_GCM,data:5LXLmBgxbdYJM5Tq69GnE/I+xuD+BuJ7X6xP5G7WjK/MI2+VQiskHGA2BodRCDenJed5udl7hTKwFJ3+BZwTnL7h/GklbvfMqScl2uiVK04pyqNsYiCWky1MX2W/Sy59LflnUNmG5I31vepxXT7v/YLYBeDWK3unIH0vwfixnJY=,iv:xdYpk73ty8wWOA8XdyqphhUOOAAjgXOsgcj1DOhJyfE=,tag:jPy46c2UiEsrZr9a7PTDwA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
