apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:v5oqQndyKyCzovXyqg2dGfbjgLK/8ndMxNNoXkwqR06dr4iZit9jTmpVYnJZ98Ge0BQSp/y4ckmAQ4KKs1KEN4TwV9qKL588heKJw93R2aC7lsvXCNsf0piPGUTmYX+rzvqZt6QUvnMJXRS4+jfoVrfVVBlikKqRjg==,iv:D5wGnzVH1dXU9XITxuhyy41o7qNQC2nvIeYxAQAsO5E=,tag:6H7K6tc4OgpP/gdCuEUgiw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTkxEZHZuK21yN1lyb0xU
            WlV4WTB3RVBtcEdiZ3J3RGl6OEVJUlVMcFhRCnBWYWdzZEJWemlKS2JGSkNtaDdX
            TGtmaHhYM3RyWU1DMzVtc0tuQjExMm8KLS0tIExXK2hyRlNIWGhmU0tobC9ydmZK
            NFoxRmJhTE5RUEx1QTJ1Ni9xV2NDUFkKN+/GvPE79v/A4W0Uct/jW5OAvUy5H/J/
            oD0exVcJyVbGa3g7EqLUlrjNwJ7KoGcNAZH1k5r9IqTqxAE3efupyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T15:48:55Z"
    mac: ENC[AES256_GCM,data:xJsXm/07pWcaD7yfKhSbS89treSfoc+AZMD6FeGACUgs3Z6XJecv5/BBtnUYmIe0sV4sEwkm8D4T1juvKD9PZ+sVBtsSOsmo5hpcY4XaLHtERVYYvokiQfSvRdzKi/fUEkC9Zl1rqDwQ2p0qpyP8OSu6yhPdNlTNcyRakXHnamY=,iv:0Qeozt1YM7rW8/dRQ9SPEK+U1pOvpqNChcHuu/Nv9WQ=,tag:Kn1s7/56LHLL3FLsXUT90w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
