apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:IUSFpiF1E+JU2QGqU7t+4n7LffmBJt4/zt6Nlq585FM9YqNyEhPxE5lMPJ9sCo/sstgIMWCxWu6aQyQbDVOP5SC1OBsuV3SX2TCDq/ojtDTpzsDDLDniy7Q9HgRikyP/D/a43fo8DtdOC9ZuwA7Gx0NCYw2BqJbDpQ==,iv:68p4h4sL3/hlbqlEHNhbBBaFaPnBOwE5MxGyrTLihss=,tag:diYtA6uXr6SXmOhSaWfiNA==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:PNrHMK8ztdehyO+pzH6gClULO6Ibdxt930Ex2GK+QT5wpBGfzIw7szBiUILTbxplAIUWLJ08U/BHGT0ll6C8KA==,iv:9rSx+FJMIMxAkgQgEovDcJkpsK5EQbbHz7erWvJlZ78=,tag:pTEB1ieBRWryduePbvXfEg==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:T6Ho+DExRMh8kofMOcl8HKhEX6YMwlIkZtexyKT1K7y6/bExF6ESZLFJKfRayEO/hM4l6WXLqzg9CT2J7xVPETNeoeLvUiDhx+XJnaDmqZYFQLmkZgN1iPrTh24=,iv:G2+oiG30TEOT3plNTvkHhbS0M/GJAGe13TrrhZ+n2rs=,tag:5fIgHCXYaw1rIBn1Avq5HA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TDV3OSsvc2pwRE9lOHBD
            TXJkYSs1bHNzbG1JMDhjb1d5QkpSQnRuS3dNCjJpVzNmWjBsU2lCMkNRVFhiOEZB
            VjFaYTRwazlpamh4RUI3a2szM3hxL3MKLS0tIEZ4bDlrOURkczV1WjVFaTNrdTNL
            ZEFaY29yMzRQSkVVS05aaENqcmwyV2cKQhotk8d5oLhu9xLfKt/ebo9971zeviME
            o9Po0SNw+TdvPd0DuRYAnhn/krLPt3WS5LjZbYnzKvjIGuNKZH9ECg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T23:11:31Z"
    mac: ENC[AES256_GCM,data:yjYGJ8oWZ3zpAW44W70rbCABYTNZQayaIof8RBuQ9d+pu+jVFFancuhB5GALza36feVowAyd1nb5LuuJFXlGw1vl+xS867o4kuOofzA2/KTv8mwho5b2edlWsz0MO4Uq++gaqhz06/t4VtvdH4cnBlL9m9/O94kzTIhNl1bdZzI=,iv:uMA/+0VmPVDkxnHrbjWn3aB/EVx0jHI/L1hORPumaKo=,tag:eIzk0WlfFlYTyiXQb6OyQQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
