apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:jnfNRhTNRfBt0VjJwgyT+3qi19JwP3OODfS8GrUVFjr3yA/zoSxVzuKZp8XBxNCC5yxBMfIewGbKOjRKPwNx5tZnnYN9iqatkv6ENOMz2nITe+nqnQH0/tEg8kkL31aM+6Aiay1xeO2fb3HPJl8InfxXkgKh7T4snA==,iv:MPJtowptG68kTpJgRCc1i1NAcQ0462xenNaotPEgkTo=,tag:BAwkOPGE6mxa+ustn8UwIg==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:JUB2ocHkn0++woB8w2GXTyqigeEsmcB2gugblDAE0rc5pAUncGc+McUTsWil6Y3Wu37dFMa2QYg6HqKe4rtjqw==,iv:/gs7cI76eZ1Kh6HSScZjSVyWAm1Hqy/v2/W6Yy1G8R4=,tag:DmppijQYaQ4In+rNx3lD5Q==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:efgYsgzeJneOmnPXXYSdhjYwVqZsr2CMiaeNNqIdVa9ug87DqG8XJIkBcJ0CLXeH7dDq2qxdZxWR2POeQ7KQKE01tN52f49iAMP+o85YW4otaQnxPGG91UAi1N0=,iv:eNEmp054NDgkfJRZqnZKsyIUJ86d2DXguv2tU1HPNK4=,tag:hoAhbZpMPDWC3LE+HRSE9Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ODRoNmVYYXBDVlJFcnln
            YkNaZ081ZnNJM2dWUk9FZWYwam1oV292dmw0CjUxTlNlZDkvellxRzcxNlNKMmhE
            bS9RVmsxVTJzYXBEQWhYbG5sbHlQL0UKLS0tIERDd0s0Vk1LdTlWZXd6b0xIZGNK
            b2tQYVp5MzBiN09NMS9MTFJhT0V0cXcK5bqo/BP5TAr05ktSoQCfHIWmEbeC9FJV
            kCOGVtZ9VvoehCKWO0alodoOp73YgchEWOhz//gAPEZKvnS1ap2G7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T22:52:52Z"
    mac: ENC[AES256_GCM,data:Rd3U3lH8ga31WuoBRPa9KEC941hH/NkeVPUPayL7b60wp+kjT20oo5ziRjaEKsjzT2ujv/PvtJ+LopzejdSuSW9EEyU18uDsHS1h+gWHefGeYr9Lss8okDzGk7bpGQdzAHDY0qcM6lUK+WAVSG9cfrXjUWBQkmzC1YuWtU1Y6yo=,iv:zA8Y/pQS6Vu9bCQstbC/oc4Wbl9LSC4BR/JHAIZZwrk=,tag:gY2jQZTSnfhtl8yji/62vA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
