apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:2OadF053Vu0lRPbb4DaqUc/eWpzU3PsBU8eXa/mUEtMRFEZbz5QUgXzKOsu5dDEkC3A3qifSfhGSS2b6a/OIZqFKNZDXtOvy3mgZimN+GN7GOKfgwanfCz1kSyTUj76IEwYnlam7OZGYcUBeC74mvBapgC7QxVAU8Q==,iv:GqoriC7azONpd4QHzFoBLx/H6wwsPJhWLecOFP2AfGg=,tag:N7Rdhzy5mqmnF9wv09z5lg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqR2NZM0xVSjd2akpxV1Vh
            c0R5SHFWRy93akdKVSsrNVRyS1ViSC8zQlg0CktNak4zRi9LbWhzQXZiMjk3TytQ
            QXRIQ25WUVg1K3krVG9udHVteUhvUkEKLS0tIEJNM1JJbHBRS1pleVRpelJ2MHVh
            UkFsNWVTUC8wY2c0Z0trRGEyYXlVTjgKKNsM7wcPHct4uMes2IZnZLIuhFb/qIgs
            YoybqMAk+kpY6mcNXxtcMMKz4zWfRporDSaj3Gpoabn9mMMWEq8czQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T16:17:39Z"
    mac: ENC[AES256_GCM,data:8ZA3Zv8jimIdsRlHZI0z5hufliwgxp0ZA/iLeFWq0/2mYu+fHEATKgmvFA0r8q5ALvzOCgE+EfO57YODMAUk+kfHfCOp/nT3bwlaPNVE0iSRoNt9PMueqG0NOYdiM9kve1bkmLrgQtHIeQAh0SsmFXqDLoA0dvS3x7xIyilZXsI=,iv:Jpc8aDIUNez39coQdaiqx1YPMQ0gIdXv3+VDMEDxOV8=,tag:fXKxLM9gcWHd8VKyKJJYng==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
