apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:jZ3GraZDpkNnROkz5G7A05PadW/iMvjZahaUJAfkApexLgKfxoXqCldY70blV+fFzsujXCjTkvj50PsxO12Xqmh/BN9ZBDnz8Jk1HIIVbkO70HFuGnY0ZeyCAESHtK7bdgT4QizXNkXd7cyteJpYUKo46dPsxLIIyg==,iv:Uahsd7H+Z43hvBErAlS17+vKv9WPpi9QO8vj8BWSVMU=,tag:kf3QVy0WRDIsArMB/R46Vw==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:crS3ybY1clN2Q+LpWmtqDRXjcw0pcwOX4C+mNa3DjsXcubM4XBeX2nfZIGOILmMBAz2jfeSLidBv5p2ZZX7tXw==,iv:DgD9tViK7bPiv1EYrbRXNWKjdDxgmqbKbEMybguHAHQ=,tag:9hzf9e6NEKMNlQLBl1GjFg==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:fZ6gnXGQ3I8edmjhCx7x8nrZB4Lrs1cqwkmHogcrFwDe9AOGkfvj9usjyze9iZEavUch5OiHkjHW4oADgVrSujAxVsYXcvtwJrKJt6g0mApd8BSSwPSBNbDeiz4=,iv:aJ9ofoG0C2eHVnLNoSyiAKKTDX1AwLKCEHXJNJYGFcs=,tag:iaVk9kFUZjpstUEbHxArMg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeC90NkZNWGdGZ0JrSHda
            VlBETmpKdTV5RzlGV3R4NVhXUUtvZFBLK3hFCnNtVUtVcFFHTGg3MXl5emoxNldj
            ZzVvVXQ0akxkUzdZRXVkRWdjM2Y2R1UKLS0tIEkrOFdRNEdrMTRjb0E3UHMyblNo
            Yjd5eno2a3dUTU9CclJEZW80SURpQk0KMlFd0a8EdtC8S20PZL2m9/RwvUsiGpUh
            NbD+CrhYEce+qUb8q3kAH3BXwfT5NsIX1cvvweQ5peg+K3JuPAXTKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T14:54:18Z"
    mac: ENC[AES256_GCM,data:de5p5cHYfCoVWwgVebVP71jM1VHJ6Lod5hlqFEXGX3Qftoa59PVlxFjsAvSefGLJ3yowTQVSsv3LBl6rUEMkWIoWtzw9qy1ce31TVSACkM1bkLcJw6xV694RBiEsBUZJjho58Y1z4pLMgWpKIp3UCWLg3Q0KiLMG4tZo7RNH5E4=,iv:yH0X196LBgiQ7Zya/LO81+wZCj4rZc3gn/RsB7itzqE=,tag:Ctso98rpvBS7a1fAJNUCJA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
