apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:lShbFhtc5O26XMJbsliIegsRowloVuBynLC3HOlf9O11NysIzB2mlrW5xPk8pdBDAFvfKmVUu19uFRo5pi4qmQ==,iv:D6mS0SpOrK03wsJvNrg3iREn8iz1vrtNUb6Z/wzo4tc=,tag:OT5TRaa28OYr0ewhmwUB+w==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:ui2SAviURa3SzgRiNLPqlHHYK4OKNybHrxb70J+7F3UURE1QVSxTe/OpSQqFK4TqtVWeDvA4c55yVebDtSale64p/PQTgfxc/bk+xT/X4qxNn9DrhekCHxG1BOs=,iv:Do/glRsNVQM4uY1OEoy1+EjiNfrBjWBv2W4psI1npZ0=,tag:wdffweNGH1HwcFDrItyBvg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age14t5222vvj72vmserlyk9za435q29jfc54hz8j6xfmynk0ew675hqs3v6lc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaFRRUkR2bm4yWWdDYWFY
            dWpNMEs1S3M0bit0dGU4MW5JV2d4TE0wV1FzCnQ3S0t6aGszVGtzU1N2Z2FTdnFk
            aDZ0RW9xa21HeTdzT0JhT3dpL25Id2MKLS0tIDc1OGk3eXpoN0xUa0JPcUxOYXNw
            cVpDbC8yWkxZa2lpT0ZZWUh0NVROYWsKD3M2fgTgFq/geSA3dwJkz0BvDsVrngMY
            gisRbWwKJCT2ZEJ/hVfXejfG1UKegFKriZWuGF9AjJKmW11/deQuUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T14:39:19Z"
    mac: ENC[AES256_GCM,data:DNE5Vn9Hd+iizeFSvTTYLK6k/bF3P0xI80QfIw8a6oKDt7okkfi2mE6IlN9XwFmT/UusFjGDXXWZpm/YBhxE45MvQQKRsTyhQ3u/fsjFwukSiUdoQUFF4i13d/hALUuz8M/wAIlxI5tBu3xvxxcpHSgFwHxqMtTkPrVJRAVuIN0=,iv:GK+Ygo4ueoIr4g3Nrdh+1xmie+o28Nmhz6GcAQIMDng=,tag:DkiWI0YYtK9tEP0JGgn5mA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
