apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: exporter-fritz
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/observability/exporter-fritz/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
