apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: twuni
    namespace: flux-system
spec:
    interval: 10m
    url: https://twuni.github.io/docker-registry.helm
    timeout: 3m
